export interface Property {
    id: string
    name: string
    teaser: string
    image: string
    sleeps: number
    bedrooms: number
    bathrooms: number
    amenities: string[]
    description: string
    images: string[]
    matterportUrl?: string
    position?: string
    pricePerNight: number
}

export const properties: Property[] = [
    {
        id: "6",
        name: "Milan Manor House",
        teaser: "Enchanting 1940s historic manor on 30 private acres",
        image: "/images/milan-manor/milan-manor-8.jpg",
        sleeps: 14,
        bedrooms: 5,
        bathrooms: 8,
        amenities: ["30 Private Acres", "Speakeasy Bar", "Pickleball Court", "Piano", "650ft Shoreline", "Historic Charm"],
        description:
            "Escape to an enchanting private manor on 30 acres of secluded beauty along Smith Mountain Lake. Immerse yourself in 1940s charm elegantly blended with midcentury modern style, offering 6,900 sq ft of bespoke luxury perfect for weddings and family travel.",
        images: [
            "/images/milan-manor/milan-manor-1.jpg",
            "/images/milan-manor/milan-manor-2.jpg",
            "/images/milan-manor/milan-manor-3.jpg",
            "/images/milan-manor/milan-manor-4.jpg",
            "/images/milan-manor/milan-manor-5.jpg",
            "/images/milan-manor/milan-manor-6.jpg",
            "/images/milan-manor/milan-manor-7.jpg",
            "/images/milan-manor/milan-manor-8.jpg",
            "/images/milan-manor/milan-manor-9.jpg",
            "/images/milan-manor/milan-manor-10.jpg",
            "/images/milan-manor/milan-manor-11.jpg",
            "/images/milan-manor/milan-manor-12.jpg",
            "/images/milan-manor/milan-manor-13.jpg",
            "/images/milan-manor/milan-manor-14.jpg",
            "/images/milan-manor/milan-manor-15.jpg",
            "/images/milan-manor/milan-manor-16.jpg",
            "/images/milan-manor/milan-manor-17.jpg",
            "/images/milan-manor/milan-manor-18.jpg",
            "/images/milan-manor/milan-manor-19.jpg",
            "/images/milan-manor/milan-manor-20.jpg",
            "/images/milan-manor/milan-manor-21.jpg",
            "/images/milan-manor/milan-manor-22.jpg",
            "/images/milan-manor/milan-manor-23.jpg",
            "/images/milan-manor/milan-manor-24.jpg",
            "/images/milan-manor/milan-manor-25.jpg",
            "/images/milan-manor/milan-manor-26.jpg",
            "/images/milan-manor/milan-manor-27.jpg",
            "/images/milan-manor/milan-manor-28.jpg",
            "/images/milan-manor/milan-manor-29.jpg",
            "/images/milan-manor/milan-manor-30.jpg",
            "/images/milan-manor/milan-manor-31.jpg",
            "/images/milan-manor/milan-manor-32.jpg",
            "/images/milan-manor/milan-manor-33.jpg",
            "/images/milan-manor/milan-manor-34.jpg",
            "/images/milan-manor/milan-manor-35.jpg",
            "/images/milan-manor/milan-manor-36.jpg",
            "/images/milan-manor/milan-manor-37.jpg",
            "/images/milan-manor/milan-manor-38.jpg",
            "/images/milan-manor/milan-manor-39.jpg",
            "/images/milan-manor/milan-manor-40.jpg",
            "/images/milan-manor/milan-manor-41.jpg",
            "/images/milan-manor/milan-manor-42.jpg",
            "/images/milan-manor/milan-manor-43.jpg",
            "/images/milan-manor/milan-manor-44.jpg",
            "/images/milan-manor/milan-manor-45.jpg",
            "/images/milan-manor/milan-manor-46.jpg",
            "/images/milan-manor/milan-manor-47.jpg",
            "/images/milan-manor/milan-manor-48.jpg",
            "/images/milan-manor/milan-manor-49.jpg",
            "/images/milan-manor/milan-manor-50.jpg",
            "/images/milan-manor/milan-manor-51.jpg",
            "/images/milan-manor/milan-manor-52.jpg",
            "/images/milan-manor/milan-manor-53.jpg",
            "/images/milan-manor/milan-manor-54.jpg",
            "/images/milan-manor/milan-manor-55.jpg",
            "/images/milan-manor/milan-manor-56.jpg",
            "/images/milan-manor/milan-manor-57.jpg",
            "/images/milan-manor/milan-manor-58.jpg",
            "/images/milan-manor/milan-manor-59.jpg",
            "/images/milan-manor/milan-manor-60.jpg",
            "/images/milan-manor/milan-manor-61.jpg",
            "/images/milan-manor/milan-manor-62.jpg",
            "/images/milan-manor/milan-manor-63.jpg",
            "/images/milan-manor/milan-manor-64.jpg",
            "/images/milan-manor/milan-manor-65.jpg",
            "/images/milan-manor/milan-manor-66.jpg",
            "/images/milan-manor/milan-manor-67.jpg",
            "/images/milan-manor/milan-manor-68.jpg",
            "/images/milan-manor/milan-manor-69.jpg",
            "/images/milan-manor/milan-manor-70.jpg",
            "/images/milan-manor/milan-manor-71.jpg",
            "/images/milan-manor/milan-manor-72.jpg",
            "/images/milan-manor/milan-manor-73.jpg",
            "/images/milan-manor/milan-manor-74.jpg",
            "/images/milan-manor/milan-manor-75.jpg",
            "/images/milan-manor/milan-manor-76.jpg",
            "/images/milan-manor/milan-manor-77.jpg",
            "/images/milan-manor/milan-manor-78.jpg",
            "/images/milan-manor/milan-manor-79.jpg",
            "/images/milan-manor/milan-manor-80.jpg",
            "/images/milan-manor/milan-manor-81.jpg",
            "/images/milan-manor/milan-manor-82.jpg",
            "/images/milan-manor/milan-manor-83.jpg",
            "/images/milan-manor/milan-manor-84.jpg",
        ],
    },
    {
        id: "1",
        name: "Suite Retreat",
        teaser: "14,000 sq ft ultimate entertainment estate for large groups",
        image: "/images/suite-retreat/suite-retreat-1.jpg",
        sleeps: 32,
        bedrooms: 9,
        bathrooms: 11,
        amenities: ["7 Suites", "2 Bunkrooms", "Bowling Alley", "Golf Simulator", "Pool & Spa", "Home Theater"],
        description:
            "A massive 14,000 sq ft luxury estate built for the ultimate group getaway. Features 7 private suites, 2 bunkrooms sleeping 12 each, an elevator, and a world-class entertainment wing with a bowling alley, golf simulator, and theater.",
        images: [
            "/images/suite-retreat/suite-retreat-1.jpg",
            "/images/suite-retreat/suite-retreat-2.jpg",
            "/images/suite-retreat/suite-retreat-3.jpg",
            "/images/suite-retreat/suite-retreat-4.jpg",
            "/images/suite-retreat/suite-retreat-5.jpg",
            "/images/suite-retreat/suite-retreat-6.jpg",
            "/images/suite-retreat/suite-retreat-7.jpg",
            "/images/suite-retreat/suite-retreat-8.jpg",
            "/images/suite-retreat/suite-retreat-9.jpg",
            "/images/suite-retreat/suite-retreat-10.jpg",
            "/images/suite-retreat/suite-retreat-11.jpg",
            "/images/suite-retreat/suite-retreat-12.jpg",
            "/images/suite-retreat/suite-retreat-13.jpg",
            "/images/suite-retreat/suite-retreat-14.jpg",
            "/images/suite-retreat/suite-retreat-15.jpg",
            "/images/suite-retreat/suite-retreat-16.jpg",
            "/images/suite-retreat/suite-retreat-17.jpg",
            "/images/suite-retreat/suite-retreat-18.jpg",
            "/images/suite-retreat/suite-retreat-19.jpg",
            "/images/suite-retreat/suite-retreat-20.jpg",
            "/images/suite-retreat/suite-retreat-21.jpg",
            "/images/suite-retreat/suite-retreat-22.jpg",
            "/images/suite-retreat/suite-retreat-23.jpg",
            "/images/suite-retreat/suite-retreat-24.jpg",
            "/images/suite-retreat/suite-retreat-25.jpg",
            "/images/suite-retreat/suite-retreat-26.jpg",
            "/images/suite-retreat/suite-retreat-27.jpg",
            "/images/suite-retreat/suite-retreat-28.jpg",
            "/images/suite-retreat/suite-retreat-29.jpg",
            "/images/suite-retreat/suite-retreat-30.jpg",
            "/images/suite-retreat/suite-retreat-31.jpg",
            "/images/suite-retreat/suite-retreat-32.jpg",
            "/images/suite-retreat/suite-retreat-33.jpg",
            "/images/suite-retreat/suite-retreat-34.jpg",
            "/images/suite-retreat/suite-retreat-35.jpg",
            "/images/suite-retreat/suite-retreat-36.jpg",
            "/images/suite-retreat/suite-retreat-37.jpg",
            "/images/suite-retreat/suite-retreat-38.jpg",
            "/images/suite-retreat/suite-retreat-39.jpg",
            "/images/suite-retreat/suite-retreat-40.jpg",
            "/images/suite-retreat/suite-retreat-41.jpg",
            "/images/suite-retreat/suite-retreat-42.jpg",
            "/images/suite-retreat/suite-retreat-43.jpg",
            "/images/suite-retreat/suite-retreat-44.jpg",
            "/images/suite-retreat/suite-retreat-45.jpg",
            "/images/suite-retreat/suite-retreat-46.jpg",
            "/images/suite-retreat/suite-retreat-47.jpg",
            "/images/suite-retreat/suite-retreat-48.jpg",
            "/images/suite-retreat/suite-retreat-49.jpg",
            "/images/suite-retreat/suite-retreat-50.jpg",
            "/images/suite-retreat/suite-retreat-51.jpg",
            "/images/suite-retreat/suite-retreat-52.jpg",
            "/images/suite-retreat/suite-retreat-53.jpg",
            "/images/suite-retreat/suite-retreat-54.jpg",
            "/images/suite-retreat/suite-retreat-55.jpg",
            "/images/suite-retreat/suite-retreat-56.jpg",
            "/images/suite-retreat/suite-retreat-57.jpg",
            "/images/suite-retreat/suite-retreat-58.jpg",
            "/images/suite-retreat/suite-retreat-59.jpg",
            "/images/suite-retreat/suite-retreat-60.jpg",
            "/images/suite-retreat/suite-retreat-61.jpg",
            "/images/suite-retreat/suite-retreat-62.jpg",
            "/images/suite-retreat/suite-retreat-63.jpg",
            "/images/suite-retreat/suite-retreat-64.jpg",
            "/images/suite-retreat/suite-retreat-65.jpg",
            "/images/suite-retreat/suite-retreat-66.jpg",
            "/images/suite-retreat/suite-retreat-67.jpg",
            "/images/suite-retreat/suite-retreat-68.jpg",
            "/images/suite-retreat/suite-retreat-69.jpg",
            "/images/suite-retreat/suite-retreat-70.jpg",
            "/images/suite-retreat/suite-retreat-71.jpg",
            "/images/suite-retreat/suite-retreat-72.jpg",
            "/images/suite-retreat/suite-retreat-73.jpg",
            "/images/suite-retreat/suite-retreat-74.jpg",
            "/images/suite-retreat/suite-retreat-75.jpg",
            "/images/suite-retreat/suite-retreat-76.jpg",
            "/images/suite-retreat/suite-retreat-77.jpg",
            "/images/suite-retreat/suite-retreat-78.jpg",
            "/images/suite-retreat/suite-retreat-79.jpg",
            "/images/suite-retreat/suite-retreat-80.jpg",
            "/images/suite-retreat/suite-retreat-81.jpg",
            "/images/suite-retreat/suite-retreat-82.jpg",
            "/images/suite-retreat/suite-retreat-83.jpg",
            "/images/suite-retreat/suite-retreat-84.jpg",
            "/images/suite-retreat/suite-retreat-85.jpg",
            "/images/suite-retreat/suite-retreat-86.jpg",
            "/images/suite-retreat/suite-retreat-87.jpg",
            "/images/suite-retreat/suite-retreat-88.jpg",
            "/images/suite-retreat/suite-retreat-89.jpg",
            "/images/suite-retreat/suite-retreat-90.jpg",
            "/images/suite-retreat/suite-retreat-91.jpg",
            "/images/suite-retreat/suite-retreat-92.jpg",
            "/images/suite-retreat/suite-retreat-93.jpg",
            "/images/suite-retreat/suite-retreat-94.jpg",
            "/images/suite-retreat/suite-retreat-95.jpg",
            "/images/suite-retreat/suite-retreat-96.jpg",
            "/images/suite-retreat/suite-retreat-97.jpg",
            "/images/suite-retreat/suite-retreat-98.jpg",
            "/images/suite-retreat/suite-retreat-99.jpg",
            "/images/suite-retreat/suite-retreat-100.jpg",
            "/images/suite-retreat/suite-retreat-101.jpg",
            "/images/suite-retreat/suite-retreat-102.jpg",
            "/images/suite-retreat/suite-retreat-103.jpg",
            "/images/suite-retreat/suite-retreat-104.jpg",
            "/images/suite-retreat/suite-retreat-105.jpg",
            "/images/suite-retreat/suite-retreat-106.jpg",
            "/images/suite-retreat/suite-retreat-107.jpg",
            "/images/suite-retreat/suite-retreat-108.jpg",
            "/images/suite-retreat/suite-retreat-109.jpg",
            "/images/suite-retreat/suite-retreat-110.jpg",
            "/images/suite-retreat/suite-retreat-111.jpg",
            "/images/suite-retreat/suite-retreat-112.jpg",
            "/images/suite-retreat/suite-retreat-113.jpg",
            "/images/suite-retreat/suite-retreat-114.jpg",
            "/images/suite-retreat/suite-retreat-115.jpg",
            "/images/suite-retreat/suite-retreat-116.jpg",
            "/images/suite-retreat/suite-retreat-117.jpg",
            "/images/suite-retreat/suite-retreat-118.jpg",
            "/images/suite-retreat/suite-retreat-119.jpg",
            "/images/suite-retreat/suite-retreat-120.jpg",
            "/images/suite-retreat/suite-retreat-121.jpg",
            "/images/suite-retreat/suite-retreat-122.jpg",
            "/images/suite-retreat/suite-retreat-123.jpg",
            "/images/suite-retreat/suite-retreat-124.jpg",
            "/images/suite-retreat/suite-retreat-125.jpg",
            "/images/suite-retreat/suite-retreat-126.jpg",
            "/images/suite-retreat/suite-retreat-127.jpg",
            "/images/suite-retreat/suite-retreat-128.jpg",
            "/images/suite-retreat/suite-retreat-129.jpg",
            "/images/suite-retreat/suite-retreat-130.jpg",
            "/images/suite-retreat/suite-retreat-131.jpg",
            "/images/suite-retreat/suite-retreat-132.jpg",
            "/images/suite-retreat/suite-retreat-133.jpg",
            "/images/suite-retreat/suite-retreat-134.jpg",
            "/images/suite-retreat/suite-retreat-135.jpg",
            "/images/suite-retreat/suite-retreat-136.jpg",
            "/images/suite-retreat/suite-retreat-137.jpg",
            "/images/suite-retreat/suite-retreat-138.jpg",
            "/images/suite-retreat/suite-retreat-139.jpg",
            "/images/suite-retreat/suite-retreat-140.jpg",
            "/images/suite-retreat/suite-retreat-141.jpg",
            "/images/suite-retreat/suite-retreat-142.jpg",
            "/images/suite-retreat/suite-retreat-143.jpg",
            "/images/suite-retreat/suite-retreat-144.jpg",
            "/images/suite-retreat/suite-retreat-145.jpg",
            "/images/suite-retreat/suite-retreat-146.jpg",
            "/images/suite-retreat/suite-retreat-147.jpg",
            "/images/suite-retreat/suite-retreat-148.jpg",
            "/images/suite-retreat/suite-retreat-149.jpg",
            "/images/suite-retreat/suite-retreat-150.jpg",
            "/images/suite-retreat/suite-retreat-151.jpg",
            "/images/suite-retreat/suite-retreat-152.jpg",
            "/images/suite-retreat/suite-retreat-153.jpg",
            "/images/suite-retreat/suite-retreat-154.jpg",
            "/images/suite-retreat/suite-retreat-155.jpg",
            "/images/suite-retreat/suite-retreat-156.jpg",
            "/images/suite-retreat/suite-retreat-157.jpg",
            "/images/suite-retreat/suite-retreat-158.jpg",
            "/images/suite-retreat/suite-retreat-159.jpg",
            "/images/suite-retreat/suite-retreat-160.jpg",
            "/images/suite-retreat/suite-retreat-161.jpg",
            "/images/suite-retreat/suite-retreat-162.jpg",
            "/images/suite-retreat/suite-retreat-163.jpg",
            "/images/suite-retreat/suite-retreat-164.jpg",
            "/images/suite-retreat/suite-retreat-165.jpg",
            "/images/suite-retreat/suite-retreat-166.jpg",
            "/images/suite-retreat/suite-retreat-167.jpg",
            "/images/suite-retreat/suite-retreat-168.jpg",
        ],
        position: "center 70%",
    },
    {
        id: "2",
        name: "Suite View",
        teaser: "13,000+ sq ft of luxury for large groups and multifamily retreats",
        image: "/images/suite-view/suite-view-1.jpg",
        sleeps: 28,
        bedrooms: 8,
        bathrooms: 9,
        amenities: ["7 Private Suites", "Large Bunkrooms", "Game Room", "Commercial Kitchen", "400ft Shoreline", "Spa", "Boat Dock"],
        description:
            "Over 13,000 square feet of vacation home living built for multifamily and large groups (28 person Capacity). Featuring 7 suites with attached bathrooms, large bunkrooms, and extensive indoor and outdoor entertainment areas including a spa and private dock.",
        images: [
            "/images/suite-view/suite-view-1.jpg",
            "/images/suite-view/suite-view-2.jpg",
            "/images/suite-view/suite-view-3.jpg",
            "/images/suite-view/suite-view-4.jpg",
            "/images/suite-view/suite-view-5.jpg",
            "/images/suite-view/suite-view-6.jpg",
            "/images/suite-view/suite-view-7.jpg",
            "/images/suite-view/suite-view-8.jpg",
            "/images/suite-view/suite-view-9.jpg",
            "/images/suite-view/suite-view-10.jpg",
            "/images/suite-view/suite-view-11.jpg",
            "/images/suite-view/suite-view-12.jpg",
            "/images/suite-view/suite-view-13.jpg",
            "/images/suite-view/suite-view-14.jpg",
            "/images/suite-view/suite-view-15.jpg",
            "/images/suite-view/suite-view-16.jpg",
            "/images/suite-view/suite-view-17.jpg",
            "/images/suite-view/suite-view-18.jpg",
            "/images/suite-view/suite-view-19.jpg",
            "/images/suite-view/suite-view-20.jpg",
            "/images/suite-view/suite-view-21.jpg",
            "/images/suite-view/suite-view-22.jpg",
            "/images/suite-view/suite-view-23.jpg",
            "/images/suite-view/suite-view-24.jpg",
            "/images/suite-view/suite-view-25.jpg",
            "/images/suite-view/suite-view-26.jpg",
            "/images/suite-view/suite-view-27.jpg",
            "/images/suite-view/suite-view-28.jpg",
            "/images/suite-view/suite-view-29.jpg",
            "/images/suite-view/suite-view-30.jpg",
            "/images/suite-view/suite-view-31.jpg",
            "/images/suite-view/suite-view-32.jpg",
            "/images/suite-view/suite-view-33.jpg",
            "/images/suite-view/suite-view-34.jpg",
            "/images/suite-view/suite-view-35.jpg",
            "/images/suite-view/suite-view-36.jpg",
            "/images/suite-view/suite-view-37.jpg",
            "/images/suite-view/suite-view-38.jpg",
            "/images/suite-view/suite-view-39.jpg",
            "/images/suite-view/suite-view-40.jpg",
            "/images/suite-view/suite-view-41.jpg",
            "/images/suite-view/suite-view-42.jpg",
            "/images/suite-view/suite-view-43.jpg",
            "/images/suite-view/suite-view-44.jpg",
            "/images/suite-view/suite-view-45.jpg",
            "/images/suite-view/suite-view-46.jpg",
            "/images/suite-view/suite-view-47.jpg",
            "/images/suite-view/suite-view-48.jpg",
            "/images/suite-view/suite-view-49.jpg",
            "/images/suite-view/suite-view-50.jpg",
            "/images/suite-view/suite-view-51.jpg",
            "/images/suite-view/suite-view-52.jpg",
            "/images/suite-view/suite-view-53.jpg",
            "/images/suite-view/suite-view-54.jpg",
            "/images/suite-view/suite-view-55.jpg",
            "/images/suite-view/suite-view-56.jpg",
            "/images/suite-view/suite-view-57.jpg",
            "/images/suite-view/suite-view-58.jpg",
            "/images/suite-view/suite-view-59.jpg",
            "/images/suite-view/suite-view-60.jpg",
            "/images/suite-view/suite-view-61.jpg",
            "/images/suite-view/suite-view-62.jpg",
            "/images/suite-view/suite-view-63.jpg",
            "/images/suite-view/suite-view-64.jpg",
            "/images/suite-view/suite-view-65.jpg",
            "/images/suite-view/suite-view-66.jpg",
            "/images/suite-view/suite-view-67.jpg",
            "/images/suite-view/suite-view-68.jpg",
            "/images/suite-view/suite-view-69.jpg",
            "/images/suite-view/suite-view-70.jpg",
            "/images/suite-view/suite-view-71.jpg",
            "/images/suite-view/suite-view-72.jpg",
            "/images/suite-view/suite-view-73.jpg",
            "/images/suite-view/suite-view-74.jpg",
            "/images/suite-view/suite-view-75.jpg",
            "/images/suite-view/suite-view-76.jpg",
            "/images/suite-view/suite-view-77.jpg",
            "/images/suite-view/suite-view-78.jpg",
            "/images/suite-view/suite-view-79.jpg",
            "/images/suite-view/suite-view-80.jpg",
            "/images/suite-view/suite-view-81.jpg",
            "/images/suite-view/suite-view-82.jpg",
            "/images/suite-view/suite-view-83.jpg",
            "/images/suite-view/suite-view-84.jpg",
            "/images/suite-view/suite-view-85.jpg",
            "/images/suite-view/suite-view-86.jpg",
            "/images/suite-view/suite-view-87.jpg",
            "/images/suite-view/suite-view-88.jpg",
            "/images/suite-view/suite-view-89.jpg",
            "/images/suite-view/suite-view-90.jpg",
            "/images/suite-view/suite-view-91.jpg",
            "/images/suite-view/suite-view-92.jpg",
            "/images/suite-view/suite-view-93.jpg",
            "/images/suite-view/suite-view-94.jpg",
            "/images/suite-view/suite-view-95.jpg",
            "/images/suite-view/suite-view-96.jpg",
            "/images/suite-view/suite-view-97.jpg",
            "/images/suite-view/suite-view-98.jpg",
            "/images/suite-view/suite-view-99.jpg",
            "/images/suite-view/suite-view-100.jpg",
            "/images/suite-view/suite-view-101.jpg",
            "/images/suite-view/suite-view-102.jpg",
            "/images/suite-view/suite-view-103.jpg",
            "/images/suite-view/suite-view-104.jpg",
            "/images/suite-view/suite-view-105.jpg",
            "/images/suite-view/suite-view-106.jpg",
            "/images/suite-view/suite-view-107.jpg",
            "/images/suite-view/suite-view-108.jpg",
            "/images/suite-view/suite-view-109.jpg",
            "/images/suite-view/suite-view-110.jpg",
            "/images/suite-view/suite-view-111.jpg",
            "/images/suite-view/suite-view-112.jpg",
            "/images/suite-view/suite-view-113.jpg",
            "/images/suite-view/suite-view-114.jpg",
            "/images/suite-view/suite-view-115.jpg",
            "/images/suite-view/suite-view-116.jpg",
            "/images/suite-view/suite-view-117.jpg",
            "/images/suite-view/suite-view-118.jpg",
            "/images/suite-view/suite-view-119.jpg",
            "/images/suite-view/suite-view-120.jpg",
            "/images/suite-view/suite-view-121.jpg",
            "/images/suite-view/suite-view-122.jpg",
            "/images/suite-view/suite-view-123.jpg",
            "/images/suite-view/suite-view-124.jpg",
            "/images/suite-view/suite-view-125.jpg",
            "/images/suite-view/suite-view-126.jpg",
            "/images/suite-view/suite-view-127.jpg",
            "/images/suite-view/suite-view-128.jpg",
            "/images/suite-view/suite-view-129.jpg",
            "/images/suite-view/suite-view-130.jpg",
            "/images/suite-view/suite-view-131.jpg",
            "/images/suite-view/suite-view-132.jpg",
            "/images/suite-view/suite-view-133.jpg",
            "/images/suite-view/suite-view-134.jpg",
            "/images/suite-view/suite-view-135.jpg",
            "/images/suite-view/suite-view-136.jpg",
            "/images/suite-view/suite-view-137.jpg",
            "/images/suite-view/suite-view-138.jpg",
            "/images/suite-view/suite-view-139.jpg",
            "/images/suite-view/suite-view-140.jpg",
            "/images/suite-view/suite-view-141.jpg",
            "/images/suite-view/suite-view-142.jpg",
            "/images/suite-view/suite-view-143.jpg",
            "/images/suite-view/suite-view-144.jpg",
            "/images/suite-view/suite-view-145.jpg",
            "/images/suite-view/suite-view-146.jpg",
            "/images/suite-view/suite-view-147.jpg",
            "/images/suite-view/suite-view-148.jpg",
            "/images/suite-view/suite-view-149.jpg",
            "/images/suite-view/suite-view-150.jpg",
            "/images/suite-view/suite-view-151.jpg",
            "/images/suite-view/suite-view-152.jpg",
            "/images/suite-view/suite-view-153.jpg",
            "/images/suite-view/suite-view-154.jpg",
            "/images/suite-view/suite-view-155.jpg",
            "/images/suite-view/suite-view-156.jpg",
            "/images/suite-view/suite-view-157.jpg",
            "/images/suite-view/suite-view-158.jpg",
            "/images/suite-view/suite-view-159.jpg",
            "/images/suite-view/suite-view-160.jpg",
            "/images/suite-view/suite-view-161.jpg",
            "/images/suite-view/suite-view-162.jpg",
            "/images/suite-view/suite-view-163.jpg",
            "/images/suite-view/suite-view-164.jpg",
            "/images/suite-view/suite-view-165.jpg",
            "/images/suite-view/suite-view-166.jpg",
            "/images/suite-view/suite-view-167.jpg",
            "/images/suite-view/suite-view-168.jpg",
            "/images/suite-view/suite-view-169.jpg",
            "/images/suite-view/suite-view-170.jpg",
            "/images/suite-view/suite-view-171.jpg",
            "/images/suite-view/suite-view-172.jpg",
            "/images/suite-view/suite-view-173.jpg",
            "/images/suite-view/suite-view-174.jpg",
            "/images/suite-view/suite-view-175.jpg",
            "/images/suite-view/suite-view-176.jpg",
            "/images/suite-view/suite-view-177.jpg",
            "/images/suite-view/suite-view-178.jpg",
            "/images/suite-view/suite-view-179.jpg",
            "/images/suite-view/suite-view-180.jpg",
            "/images/suite-view/suite-view-181.jpg",
            "/images/suite-view/suite-view-182.jpg",
            "/images/suite-view/suite-view-183.jpg",
            "/images/suite-view/suite-view-184.jpg",
            "/images/suite-view/suite-view-185.jpg",
            "/images/suite-view/suite-view-186.jpg",
            "/images/suite-view/suite-view-187.jpg",
            "/images/suite-view/suite-view-188.jpg",
            "/images/suite-view/suite-view-189.jpg",
            "/images/suite-view/suite-view-190.jpg",
            "/images/suite-view/suite-view-191.jpg",
            "/images/suite-view/suite-view-192.jpg",
            "/images/suite-view/suite-view-193.jpg",
        ],
    },
    {
        id: "5",
        name: "Lake View",
        teaser: "Luxury 2-bedroom condo with stunning waterfront views and 3D tour",
        image: "/photos/lake-view/thumbnail.jpg",
        sleeps: 6,
        bedrooms: 2,
        bathrooms: 2,
        amenities: ["Waterfront Views", "3D Tour", "Screened Decks", "Traeger Grill", "Swim Dock", "Wi-Fi"],
        description:
            "Beautiful 2-bedroom, 2-bath ground floor condo offering 1,040 sq ft of comfortable living space. Features stunning waterfront views, fully equipped kitchen, private decks, and access to a swim dock and boat docking.",
        images: [
            "/images/lake-view/lake-view-1.jpg",
            "/images/lake-view/lake-view-2.jpg",
            "/images/lake-view/lake-view-3.jpg",
            "/images/lake-view/lake-view-4.jpg",
            "/images/lake-view/lake-view-5.jpg",
            "/images/lake-view/lake-view-6.jpg",
            "/images/lake-view/lake-view-7.jpg",
            "/images/lake-view/lake-view-8.jpg",
            "/images/lake-view/lake-view-9.jpg",
            "/images/lake-view/lake-view-10.jpg",
            "/images/lake-view/lake-view-11.jpg",
            "/images/lake-view/lake-view-12.jpg",
            "/images/lake-view/lake-view-13.jpg",
            "/images/lake-view/lake-view-14.jpg",
            "/images/lake-view/lake-view-15.jpg",
            "/images/lake-view/lake-view-16.jpg",
            "/images/lake-view/lake-view-17.jpg",
            "/images/lake-view/lake-view-18.jpg",
            "/images/lake-view/lake-view-19.jpg",
            "/images/lake-view/lake-view-20.jpg",
            "/images/lake-view/lake-view-21.jpg",
            "/images/lake-view/lake-view-22.jpg",
            "/images/lake-view/lake-view-23.jpg",
            "/images/lake-view/lake-view-24.jpg",
            "/images/lake-view/lake-view-25.jpg",
        ],
        matterportUrl: "https://my.matterport.com/show/?m=vih9WU3PNQj"
    },
    {
        id: "7",
        name: "Penthouse View",
        teaser: "Stunning 3-bedroom penthouse with private decks and long water views",
        image: "/images/penthouse-view/penthouse-view-1.jpg",
        sleeps: 8,
        bedrooms: 3,
        bathrooms: 3,
        amenities: ["Penthouse Views", "3D Tour", "Traeger Grill", "Swim Dock", "Elevator", "Screened Decks"],
        description:
            "Stunning 3-bedroom penthouse condo featuring 1,453 sq ft of luxury living. Enjoy breathtaking long water views from private screened and open-air decks, a fully equipped gourmet kitchen, and direct access to swimming and fishing docks.",
        images: [
            "/images/penthouse-view/penthouse-view-1.jpg",
            "/images/penthouse-view/penthouse-view-2.jpg",
            "/images/penthouse-view/penthouse-view-3.jpg",
            "/images/penthouse-view/penthouse-view-4.jpg",
            "/images/penthouse-view/penthouse-view-5.jpg",
            "/images/penthouse-view/penthouse-view-6.jpg",
            "/images/penthouse-view/penthouse-view-7.jpg",
            "/images/penthouse-view/penthouse-view-8.jpg",
            "/images/penthouse-view/penthouse-view-9.jpg",
            "/images/penthouse-view/penthouse-view-10.jpg",
            "/images/penthouse-view/penthouse-view-11.jpg",
            "/images/penthouse-view/penthouse-view-12.jpg",
            "/images/penthouse-view/penthouse-view-13.jpg",
            "/images/penthouse-view/penthouse-view-14.jpg",
            "/images/penthouse-view/penthouse-view-15.jpg",
            "/images/penthouse-view/penthouse-view-16.jpg",
            "/images/penthouse-view/penthouse-view-17.jpg",
            "/images/penthouse-view/penthouse-view-18.jpg",
            "/images/penthouse-view/penthouse-view-19.jpg",
            "/images/penthouse-view/penthouse-view-20.jpg",
            "/images/penthouse-view/penthouse-view-21.jpg",
            "/images/penthouse-view/penthouse-view-22.jpg",
            "/images/penthouse-view/penthouse-view-23.jpg",
            "/images/penthouse-view/penthouse-view-24.jpg",
            "/images/penthouse-view/penthouse-view-25.jpg",
            "/images/penthouse-view/penthouse-view-26.jpg",
            "/images/penthouse-view/penthouse-view-27.jpg",
            "/images/penthouse-view/penthouse-view-28.jpg",
            "/images/penthouse-view/penthouse-view-29.jpg",
            "/images/penthouse-view/penthouse-view-30.jpg",
            "/images/penthouse-view/penthouse-view-31.jpg",
            "/images/penthouse-view/penthouse-view-32.jpg",
            "/images/penthouse-view/penthouse-view-33.jpg",
        ],
        matterportUrl: "https://my.matterport.com/show/?m=bRM4Kkhfu6T"
    },
]

// Mock Availability Logic
export function getMockAvailability(propertyId: string, month: number, year: number): number[] {
    // Deterministic pseudo-random based on propertyId + month + year
    // seed ensures the same "random" days are always booked for a specific property/month combo
    const seed = (propertyId?.charCodeAt(0) || 0) + month + year
    const daysInMonth = new Date(year, month + 1, 0).getDate()
    const bookedDays: number[] = []

    for (let day = 1; day <= daysInMonth; day++) {
        // Simple algo to mark random days as booked (approx 20% occupancy to make it interesting)
        const pseudoRandom = Math.abs(Math.sin(seed * day * 1337))
        if (pseudoRandom > 0.8) {
            bookedDays.push(day)
        }
    }
    return bookedDays
}

export function isDateUnavailable(date: Date, propertyId?: string): boolean {
    // If no property selected, we'll be lenient and say generally available unless specifically checking
    // But for the calendar visual, we might want to show some generic busy dates if "All" is selected
    const pid = propertyId || "generic"
    const booked = getMockAvailability(pid, date.getMonth(), date.getFullYear())
    return booked.includes(date.getDate())
}
