export interface Property {
    id: string
    name: string
    teaser: string
    image: string
    sleeps: number
    bedrooms: number
    bathrooms: number
    amenities: string[]
    description: string
    images: string[]
    matterportUrl?: string
    position?: string
    pricePerNight: number
    lat: number
    lng: number
    hostawayId?: string
    videoUrl?: string
}

export const properties: Property[] = [
    {
        id: "1",
        name: "Suite Retreat",
        teaser: "A 14,000-SqFt Lakefront Estate for Elevated Gatherings",
        image: "/images/suite-retreat/suite-retreat-1.jpg",
        sleeps: 32,
        bedrooms: 9,
        bathrooms: 11,
        amenities: [
            "7 private suites (each with attached bathroom)",
            "2 oversized bunkrooms (each sleeps 12)",
            "Sleeps up to 32 guests",
            "Large-screen TVs in suites and bunkrooms",
            "Coffee bars in suites",
            "Beverage refrigerators in suites",
            "Gourmet kitchen",
            "Two laundry rooms",
            "Elevator",
            "Ice makers",
            "Bowling alley",
            "Golf simulator",
            "Pool table",
            "Ping pong",
            "Air hockey",
            "Skee ball",
            "Arcade games",
            "Pool",
            "Spa",
            "Kayaks",
            "Paddle boards",
            "Life jackets",
            "Grill",
            "Green Egg Smoker"
        ],
        videoUrl: "https://www.youtube.com/watch?v=-qCN3DhAXcE",
        description:
            "Suite Retreat is a 14,000-square-foot lakefront estate designed for large families, groups, and executive gatherings. The home features seven private suites—including a 1,000-square-foot lake-facing primary suite with a spa bathroom, separate kids' wing with additional laundry room, coffee bars, beverage refrigerators, and large-screen TVs. The two spacious bunkrooms each accommodate 12 guests and include storage lockers, full bathrooms, TVs, and outdoor patios. " +
            "Inside, the entertainment wing offers a private bowling alley, advanced golf simulator, pool and ping pong tables, air hockey, skee ball, and arcade games, while the gourmet kitchen, full bar, large-screen TV overlooks, two laundry rooms, elevator, and ice makers add convenience and luxury at every turn. " +
            "Outside, the property includes a pool, spa, large patio with grill and smoker, kayaks, paddle boards, and life jackets. Multiple levels of patios and decks overlook 400 feet of private shoreline and a private dock, with endless water views through floor-to-ceiling windows. This home redefines elevated lakefront living on Smith Mountain Lake.",
        images: [
            "/images/suite-retreat/suite-retreat-1.jpg",
            "/images/suite-retreat/suite-retreat-2.jpg",
            "/images/suite-retreat/suite-retreat-3.jpg",
            "/images/suite-retreat/suite-retreat-4.jpg",
            "/images/suite-retreat/suite-retreat-5.jpg",
            "/images/suite-retreat/suite-retreat-6.jpg",
            "/images/suite-retreat/suite-retreat-7.jpg",
            "/images/suite-retreat/suite-retreat-8.jpg",
            "/images/suite-retreat/suite-retreat-9.jpg",
            "/images/suite-retreat/suite-retreat-10.jpg",
            "/images/suite-retreat/suite-retreat-11.jpg",
            "/images/suite-retreat/suite-retreat-12.jpg",
            "/images/suite-retreat/suite-retreat-13.jpg",
            "/images/suite-retreat/suite-retreat-14.jpg",
            "/images/suite-retreat/suite-retreat-15.jpg",
            "/images/suite-retreat/suite-retreat-16.jpg",
            "/images/suite-retreat/suite-retreat-17.jpg",
            "/images/suite-retreat/suite-retreat-18.jpg",
            "/images/suite-retreat/suite-retreat-19.jpg",
            "/images/suite-retreat/suite-retreat-20.jpg",
            "/images/suite-retreat/suite-retreat-21.jpg",
            "/images/suite-retreat/suite-retreat-22.jpg",
            "/images/suite-retreat/suite-retreat-23.jpg",
            "/images/suite-retreat/suite-retreat-24.jpg",
            "/images/suite-retreat/suite-retreat-25.jpg",
            "/images/suite-retreat/suite-retreat-26.jpg",
            "/images/suite-retreat/suite-retreat-27.jpg",
            "/images/suite-retreat/suite-retreat-28.jpg",
            "/images/suite-retreat/suite-retreat-29.jpg",
            "/images/suite-retreat/suite-retreat-30.jpg",
            "/images/suite-retreat/suite-retreat-31.jpg",
            "/images/suite-retreat/suite-retreat-32.jpg",
            "/images/suite-retreat/suite-retreat-33.jpg",
            "/images/suite-retreat/suite-retreat-34.jpg",
            "/images/suite-retreat/suite-retreat-35.jpg",
            "/images/suite-retreat/suite-retreat-36.jpg",
            "/images/suite-retreat/suite-retreat-37.jpg",
            "/images/suite-retreat/suite-retreat-38.jpg",
            "/images/suite-retreat/suite-retreat-39.jpg",
            "/images/suite-retreat/suite-retreat-40.jpg",
            "/images/suite-retreat/suite-retreat-41.jpg",
            "/images/suite-retreat/suite-retreat-42.jpg",
            "/images/suite-retreat/suite-retreat-43.jpg",
            "/images/suite-retreat/suite-retreat-44.jpg",
            "/images/suite-retreat/suite-retreat-45.jpg",
            "/images/suite-retreat/suite-retreat-46.jpg",
            "/images/suite-retreat/suite-retreat-47.jpg",
            "/images/suite-retreat/suite-retreat-48.jpg",
            "/images/suite-retreat/suite-retreat-49.jpg",
            "/images/suite-retreat/suite-retreat-50.jpg",
            "/images/suite-retreat/suite-retreat-51.jpg",
            "/images/suite-retreat/suite-retreat-52.jpg",
            "/images/suite-retreat/suite-retreat-53.jpg",
            "/images/suite-retreat/suite-retreat-54.jpg",
            "/images/suite-retreat/suite-retreat-55.jpg",
            "/images/suite-retreat/suite-retreat-56.jpg",
            "/images/suite-retreat/suite-retreat-57.jpg",
            "/images/suite-retreat/suite-retreat-58.jpg",
            "/images/suite-retreat/suite-retreat-59.jpg",
            "/images/suite-retreat/suite-retreat-60.jpg",
            "/images/suite-retreat/suite-retreat-61.jpg",
            "/images/suite-retreat/suite-retreat-62.jpg",
            "/images/suite-retreat/suite-retreat-63.jpg",
            "/images/suite-retreat/suite-retreat-64.jpg",
            "/images/suite-retreat/suite-retreat-65.jpg",
            "/images/suite-retreat/suite-retreat-66.jpg",
            "/images/suite-retreat/suite-retreat-67.jpg",
            "/images/suite-retreat/suite-retreat-68.jpg",
            "/images/suite-retreat/suite-retreat-69.jpg",
            "/images/suite-retreat/suite-retreat-70.jpg",
            "/images/suite-retreat/suite-retreat-71.jpg",
            "/images/suite-retreat/suite-retreat-72.jpg",
            "/images/suite-retreat/suite-retreat-73.jpg",
            "/images/suite-retreat/suite-retreat-74.jpg",
            "/images/suite-retreat/suite-retreat-75.jpg",
            "/images/suite-retreat/suite-retreat-76.jpg",
            "/images/suite-retreat/suite-retreat-77.jpg",
            "/images/suite-retreat/suite-retreat-78.jpg",
            "/images/suite-retreat/suite-retreat-79.jpg",
            "/images/suite-retreat/suite-retreat-80.jpg",
            "/images/suite-retreat/suite-retreat-81.jpg",
            "/images/suite-retreat/suite-retreat-82.jpg",
            "/images/suite-retreat/suite-retreat-83.jpg",
            "/images/suite-retreat/suite-retreat-84.jpg",
            "/images/suite-retreat/suite-retreat-85.jpg",
            "/images/suite-retreat/suite-retreat-86.jpg",
            "/images/suite-retreat/suite-retreat-87.jpg",
            "/images/suite-retreat/suite-retreat-88.jpg",
            "/images/suite-retreat/suite-retreat-89.jpg",
            "/images/suite-retreat/suite-retreat-90.jpg",
            "/images/suite-retreat/suite-retreat-91.jpg",
            "/images/suite-retreat/suite-retreat-92.jpg",
            "/images/suite-retreat/suite-retreat-93.jpg",
            "/images/suite-retreat/suite-retreat-94.jpg",
            "/images/suite-retreat/suite-retreat-95.jpg",
            "/images/suite-retreat/suite-retreat-96.jpg",
            "/images/suite-retreat/suite-retreat-97.jpg",
            "/images/suite-retreat/suite-retreat-98.jpg",
            "/images/suite-retreat/suite-retreat-99.jpg",
            "/images/suite-retreat/suite-retreat-100.jpg",
            "/images/suite-retreat/suite-retreat-101.jpg",
            "/images/suite-retreat/suite-retreat-102.jpg",
            "/images/suite-retreat/suite-retreat-103.jpg",
            "/images/suite-retreat/suite-retreat-104.jpg",
            "/images/suite-retreat/suite-retreat-105.jpg",
            "/images/suite-retreat/suite-retreat-106.jpg",
            "/images/suite-retreat/suite-retreat-107.jpg",
            "/images/suite-retreat/suite-retreat-108.jpg",
            "/images/suite-retreat/suite-retreat-109.jpg",
            "/images/suite-retreat/suite-retreat-110.jpg",
            "/images/suite-retreat/suite-retreat-111.jpg",
            "/images/suite-retreat/suite-retreat-112.jpg",
            "/images/suite-retreat/suite-retreat-113.jpg",
            "/images/suite-retreat/suite-retreat-114.jpg",
            "/images/suite-retreat/suite-retreat-115.jpg",
            "/images/suite-retreat/suite-retreat-116.jpg",
            "/images/suite-retreat/suite-retreat-117.jpg",
            "/images/suite-retreat/suite-retreat-118.jpg",
            "/images/suite-retreat/suite-retreat-119.jpg",
            "/images/suite-retreat/suite-retreat-120.jpg",
            "/images/suite-retreat/suite-retreat-121.jpg",
            "/images/suite-retreat/suite-retreat-122.jpg",
            "/images/suite-retreat/suite-retreat-123.jpg",
            "/images/suite-retreat/suite-retreat-124.jpg",
            "/images/suite-retreat/suite-retreat-125.jpg",
            "/images/suite-retreat/suite-retreat-126.jpg",
            "/images/suite-retreat/suite-retreat-127.jpg",
            "/images/suite-retreat/suite-retreat-128.jpg",
            "/images/suite-retreat/suite-retreat-129.jpg",
            "/images/suite-retreat/suite-retreat-130.jpg",
            "/images/suite-retreat/suite-retreat-131.jpg",
            "/images/suite-retreat/suite-retreat-132.jpg",
            "/images/suite-retreat/suite-retreat-133.jpg",
            "/images/suite-retreat/suite-retreat-134.jpg",
            "/images/suite-retreat/suite-retreat-135.jpg",
            "/images/suite-retreat/suite-retreat-136.jpg",
            "/images/suite-retreat/suite-retreat-137.jpg",
            "/images/suite-retreat/suite-retreat-138.jpg",
            "/images/suite-retreat/suite-retreat-139.jpg",
            "/images/suite-retreat/suite-retreat-140.jpg",
            "/images/suite-retreat/suite-retreat-141.jpg",
            "/images/suite-retreat/suite-retreat-142.jpg",
            "/images/suite-retreat/suite-retreat-143.jpg",
            "/images/suite-retreat/suite-retreat-144.jpg",
            "/images/suite-retreat/suite-retreat-145.jpg",
            "/images/suite-retreat/suite-retreat-146.jpg",
            "/images/suite-retreat/suite-retreat-147.jpg",
            "/images/suite-retreat/suite-retreat-148.jpg",
            "/images/suite-retreat/suite-retreat-149.jpg",
            "/images/suite-retreat/suite-retreat-150.jpg",
            "/images/suite-retreat/suite-retreat-151.jpg",
            "/images/suite-retreat/suite-retreat-152.jpg",
            "/images/suite-retreat/suite-retreat-153.jpg",
            "/images/suite-retreat/suite-retreat-154.jpg",
            "/images/suite-retreat/suite-retreat-155.jpg",
            "/images/suite-retreat/suite-retreat-156.jpg",
            "/images/suite-retreat/suite-retreat-157.jpg",
            "/images/suite-retreat/suite-retreat-158.jpg",
            "/images/suite-retreat/suite-retreat-159.jpg",
            "/images/suite-retreat/suite-retreat-160.jpg",
            "/images/suite-retreat/suite-retreat-161.jpg",
            "/images/suite-retreat/suite-retreat-162.jpg",
            "/images/suite-retreat/suite-retreat-163.jpg",
            "/images/suite-retreat/suite-retreat-164.jpg",
            "/images/suite-retreat/suite-retreat-165.jpg",
            "/images/suite-retreat/suite-retreat-166.jpg",
            "/images/suite-retreat/suite-retreat-167.jpg",
            "/images/suite-retreat/suite-retreat-168.jpg",
            "/images/suite-retreat/suite-retreat-169.jpg",
            "/images/suite-retreat/suite-retreat-170.jpg",
            "/images/suite-retreat/suite-retreat-171.jpg",
            "/images/suite-retreat/suite-retreat-172.jpg",
            "/images/suite-retreat/suite-retreat-173.jpg",
            "/images/suite-retreat/suite-retreat-174.jpg",
            "/images/suite-retreat/suite-retreat-175.jpg",
            "/images/suite-retreat/suite-retreat-176.jpg",
            "/images/suite-retreat/suite-retreat-177.jpg",
            "/images/suite-retreat/suite-retreat-178.jpg",
            "/images/suite-retreat/suite-retreat-179.jpg",
            "/images/suite-retreat/suite-retreat-180.jpg",
            "/images/suite-retreat/suite-retreat-181.jpg",
            "/images/suite-retreat/suite-retreat-182.jpg",
            "/images/suite-retreat/suite-retreat-183.jpg",
            "/images/suite-retreat/suite-retreat-184.jpg",
            "/images/suite-retreat/suite-retreat-185.jpg",
            "/images/suite-retreat/suite-retreat-186.jpg",
            "/images/suite-retreat/suite-retreat-187.jpg",
            "/images/suite-retreat/suite-retreat-188.jpg",
            "/images/suite-retreat/suite-retreat-189.jpg",
            "/images/suite-retreat/suite-retreat-190.jpg",
            "/images/suite-retreat/suite-retreat-191.jpg",
            "/images/suite-retreat/suite-retreat-192.jpg",
            "/images/suite-retreat/suite-retreat-193.jpg",
            "/images/suite-retreat/suite-retreat-194.jpg",
            "/images/suite-retreat/suite-retreat-195.jpg",
            "/images/suite-retreat/suite-retreat-196.jpg",
            "/images/suite-retreat/suite-retreat-197.jpg",
            "/images/suite-retreat/suite-retreat-198.jpg",
            "/images/suite-retreat/suite-retreat-199.jpg",
            "/images/suite-retreat/suite-retreat-200.jpg",
            "/images/suite-retreat/suite-retreat-201.jpg",
            "/images/suite-retreat/suite-retreat-202.jpg",
            "/images/suite-retreat/suite-retreat-203.jpg",
            "/images/suite-retreat/suite-retreat-204.jpg",
            "/images/suite-retreat/suite-retreat-205.jpg",
            "/images/suite-retreat/suite-retreat-206.jpg",
            "/images/suite-retreat/suite-retreat-207.jpg",
            "/images/suite-retreat/suite-retreat-208.jpg",
            "/images/suite-retreat/suite-retreat-209.jpg",
            "/images/suite-retreat/suite-retreat-210.jpg",
            "/images/suite-retreat/suite-retreat-211.jpg",
            "/images/suite-retreat/suite-retreat-212.jpg",
            "/images/suite-retreat/suite-retreat-213.jpg",
            "/images/suite-retreat/suite-retreat-214.jpg",
            "/images/suite-retreat/suite-retreat-215.jpg",
            "/images/suite-retreat/suite-retreat-216.jpg",
            "/images/suite-retreat/suite-retreat-217.jpg",
            "/images/suite-retreat/suite-retreat-218.jpg",
            "/images/suite-retreat/suite-retreat-219.jpg",
            "/images/suite-retreat/suite-retreat-220.jpg",
            "/images/suite-retreat/suite-retreat-221.jpg",
            "/images/suite-retreat/suite-retreat-222.jpg",
            "/images/suite-retreat/suite-retreat-223.jpg",
            "/images/suite-retreat/suite-retreat-224.jpg",
            "/images/suite-retreat/suite-retreat-225.jpg",
            "/images/suite-retreat/suite-retreat-226.jpg",
            "/images/suite-retreat/suite-retreat-227.jpg",
            "/images/suite-retreat/suite-retreat-228.jpg",
            "/images/suite-retreat/suite-retreat-229.jpg",
            "/images/suite-retreat/suite-retreat-230.jpg",
            "/images/suite-retreat/suite-retreat-231.jpg",
            "/images/suite-retreat/suite-retreat-232.jpg",
            "/images/suite-retreat/suite-retreat-233.jpg",
            "/images/suite-retreat/suite-retreat-234.jpg",
            "/images/suite-retreat/suite-retreat-235.jpg",
            "/images/suite-retreat/suite-retreat-236.jpg",
            "/images/suite-retreat/suite-retreat-237.jpg",
            "/images/suite-retreat/suite-retreat-238.jpg",
            "/images/suite-retreat/suite-retreat-239.jpg",
            "/images/suite-retreat/suite-retreat-240.jpg",
            "/images/suite-retreat/suite-retreat-241.jpg",
            "/images/suite-retreat/suite-retreat-242.jpg",
            "/images/suite-retreat/suite-retreat-243.jpg",
            "/images/suite-retreat/suite-retreat-244.jpg",
            "/images/suite-retreat/suite-retreat-245.jpg",
            "/images/suite-retreat/suite-retreat-246.jpg",
            "/images/suite-retreat/suite-retreat-247.jpg",
            "/images/suite-retreat/suite-retreat-248.jpg",
            "/images/suite-retreat/suite-retreat-249.jpg",
            "/images/suite-retreat/suite-retreat-250.jpg",
            "/images/suite-retreat/suite-retreat-251.jpg",
            "/images/suite-retreat/suite-retreat-252.jpg",
            "/images/suite-retreat/suite-retreat-253.jpg",
            "/images/suite-retreat/suite-retreat-254.jpg",
            "/images/suite-retreat/suite-retreat-255.jpg",
            "/images/suite-retreat/suite-retreat-256.jpg",
            "/images/suite-retreat/suite-retreat-257.jpg",
            "/images/suite-retreat/suite-retreat-258.jpg",
            "/images/suite-retreat/suite-retreat-259.jpg",
            "/images/suite-retreat/suite-retreat-260.jpg",
            "/images/suite-retreat/suite-retreat-261.jpg",
            "/images/suite-retreat/suite-retreat-262.jpg",
            "/images/suite-retreat/suite-retreat-263.jpg",
            "/images/suite-retreat/suite-retreat-264.jpg",
            "/images/suite-retreat/suite-retreat-265.jpg",
            "/images/suite-retreat/suite-retreat-266.jpg",
            "/images/suite-retreat/suite-retreat-267.jpg",
            "/images/suite-retreat/suite-retreat-268.jpg",
            "/images/suite-retreat/suite-retreat-269.jpg",
            "/images/suite-retreat/suite-retreat-270.jpg",
            "/images/suite-retreat/suite-retreat-271.jpg",
            "/images/suite-retreat/suite-retreat-272.jpg",
            "/images/suite-retreat/suite-retreat-273.jpg",
            "/images/suite-retreat/suite-retreat-274.jpg",
            "/images/suite-retreat/suite-retreat-275.jpg",
            "/images/suite-retreat/suite-retreat-276.jpg",
            "/images/suite-retreat/suite-retreat-277.jpg",
            "/images/suite-retreat/suite-retreat-278.jpg",
            "/images/suite-retreat/suite-retreat-279.jpg",
            "/images/suite-retreat/suite-retreat-280.jpg",
            "/images/suite-retreat/suite-retreat-281.jpg",
            "/images/suite-retreat/suite-retreat-282.jpg",
            "/images/suite-retreat/suite-retreat-283.jpg",
            "/images/suite-retreat/suite-retreat-284.jpg",
            "/images/suite-retreat/suite-retreat-285.jpg",
            "/images/suite-retreat/suite-retreat-286.jpg",
            "/images/suite-retreat/suite-retreat-287.jpg",
            "/images/suite-retreat/suite-retreat-288.jpg",
            "/images/suite-retreat/suite-retreat-289.jpg",
            "/images/suite-retreat/suite-retreat-290.jpg",
            "/images/suite-retreat/suite-retreat-291.jpg",
            "/images/suite-retreat/suite-retreat-292.jpg",
            "/images/suite-retreat/suite-retreat-293.jpg",
            "/images/suite-retreat/suite-retreat-294.jpg",
            "/images/suite-retreat/suite-retreat-295.jpg",
            "/images/suite-retreat/suite-retreat-296.jpg",
            "/images/suite-retreat/suite-retreat-297.jpg",
            "/images/suite-retreat/suite-retreat-298.jpg",
            "/images/suite-retreat/suite-retreat-299.jpg",
            "/images/suite-retreat/suite-retreat-300.jpg",
            "/images/suite-retreat/suite-retreat-301.jpg",
            "/images/suite-retreat/suite-retreat-302.jpg",
            "/images/suite-retreat/suite-retreat-303.jpg",
            "/images/suite-retreat/suite-retreat-304.jpg",
            "/images/suite-retreat/suite-retreat-305.jpg",
            "/images/suite-retreat/suite-retreat-306.jpg",
            "/images/suite-retreat/suite-retreat-307.jpg",
            "/images/suite-retreat/suite-retreat-308.jpg",
            "/images/suite-retreat/suite-retreat-309.jpg",
            "/images/suite-retreat/suite-retreat-310.jpg",
            "/images/suite-retreat/suite-retreat-311.jpg",
            "/images/suite-retreat/suite-retreat-312.jpg",
            "/images/suite-retreat/suite-retreat-313.jpg",
            "/images/suite-retreat/suite-retreat-314.jpg",
            "/images/suite-retreat/suite-retreat-315.jpg",
            "/images/suite-retreat/suite-retreat-316.jpg",
            "/images/suite-retreat/suite-retreat-317.jpg",
            "/images/suite-retreat/suite-retreat-318.jpg",
            "/images/suite-retreat/suite-retreat-319.jpg",
            "/images/suite-retreat/suite-retreat-320.jpg",
            "/images/suite-retreat/suite-retreat-321.jpg",
            "/images/suite-retreat/suite-retreat-322.jpg",
            "/images/suite-retreat/suite-retreat-323.jpg",
            "/images/suite-retreat/suite-retreat-324.jpg",
            "/images/suite-retreat/suite-retreat-325.jpg",
            "/images/suite-retreat/suite-retreat-326.jpg",
            "/images/suite-retreat/suite-retreat-327.jpg",
            "/images/suite-retreat/suite-retreat-328.jpg",
            "/images/suite-retreat/suite-retreat-329.jpg",
            "/images/suite-retreat/suite-retreat-330.jpg",
            "/images/suite-retreat/suite-retreat-331.jpg",
            "/images/suite-retreat/suite-retreat-332.jpg",
            "/images/suite-retreat/suite-retreat-333.jpg",
            "/images/suite-retreat/suite-retreat-334.jpg",
            "/images/suite-retreat/suite-retreat-335.jpg",
            "/images/suite-retreat/suite-retreat-336.jpg",
            "/images/suite-retreat/suite-retreat-337.jpg",
            "/images/suite-retreat/suite-retreat-338.jpg",
            "/images/suite-retreat/suite-retreat-339.jpg",
            "/images/suite-retreat/suite-retreat-340.jpg",
            "/images/suite-retreat/suite-retreat-341.jpg",
            "/images/suite-retreat/suite-retreat-342.jpg"
        ],
        pricePerNight: 2500,
        lat: 37.104681,
        lng: -79.655861,
        hostawayId: "466647",
    },
    {
        id: "2",
        name: "Suite View",
        teaser: "13,000+ Sq Ft of Waterfront Luxury for Multifamily Retreats",
        image: "/images/suite-view/suite-view-1.jpg",
        sleeps: 28,
        bedrooms: 8,
        bathrooms: 9,
        amenities: [
            "7 private suites (each with attached bathroom)",
            "1 oversized bunkroom",
            "Sleeps up to 28 guests",
            "Large-screen TVs throughout",
            "Coffee bars in suites",
            "Gourmet kitchen",
            "Two laundry rooms",
            "Ice makers",
            "Golf & gaming simulator",
            "Pool table, air hockey, skee ball",
            "Arcade games",
            "Pool & spa",
            "Private dock & dock bar",
            "Kayaks, paddle boards & life jackets",
            "Grill, Green Egg smoker & pizza oven"
        ],
        videoUrl: "https://www.youtube.com/watch?v=oWxMecjMrb4",
        description:
            "Suite View is a 13,000-square-foot luxury lakefront estate designed for large families and groups, offering seven private suites and one oversized bunkroom that together sleep up to 28 guests. Each suite includes an attached bathroom, large-screen TV, coffee bar, and beverage refrigerator, while the bunkroom features six queen beds and two twin beds, two TVs, two full bathrooms, and locker-style storage.\n\n" +
            "Inside, the home balances refined comfort with serious entertainment, featuring a gourmet kitchen with commercial-grade appliances, two laundry rooms, ice makers, and two entertainment areas equipped with a full bar, golf and gaming simulator, pool table, air hockey, skee ball, and arcade games.\n\n" +
            "Outside, Suite View extends the experience with a pool, outdoor kitchen, screened porch, sun deck, and two covered patios that make indoor–outdoor living effortless. A dock bar and private dock keep the lake at the center of every day, from morning coffee to sunset drinks—delivering an elevated, turnkey Smith Mountain Lake stay for multifamily retreats and large groups alike.",
        images: [
            "/images/suite-view/suite-view-1.jpg",
            "/images/suite-view/suite-view-2.jpg",
            "/images/suite-view/suite-view-3.jpg",
            "/images/suite-view/suite-view-4.jpg",
            "/images/suite-view/suite-view-5.jpg",
            "/images/suite-view/suite-view-6.jpg",
            "/images/suite-view/suite-view-7.jpg",
            "/images/suite-view/suite-view-8.jpg",
            "/images/suite-view/suite-view-9.jpg",
            "/images/suite-view/suite-view-10.jpg",
            "/images/suite-view/suite-view-11.jpg",
            "/images/suite-view/suite-view-12.jpg",
            "/images/suite-view/suite-view-13.jpg",
            "/images/suite-view/suite-view-14.jpg",
            "/images/suite-view/suite-view-15.jpg",
            "/images/suite-view/suite-view-16.jpg",
            "/images/suite-view/suite-view-17.jpg",
            "/images/suite-view/suite-view-18.jpg",
            "/images/suite-view/suite-view-19.jpg",
            "/images/suite-view/suite-view-20.jpg",
            "/images/suite-view/suite-view-21.jpg",
            "/images/suite-view/suite-view-22.jpg",
            "/images/suite-view/suite-view-23.jpg",
            "/images/suite-view/suite-view-24.jpg",
            "/images/suite-view/suite-view-25.jpg",
            "/images/suite-view/suite-view-26.jpg",
            "/images/suite-view/suite-view-27.jpg",
            "/images/suite-view/suite-view-28.jpg",
            "/images/suite-view/suite-view-29.jpg",
            "/images/suite-view/suite-view-30.jpg",
            "/images/suite-view/suite-view-31.jpg",
            "/images/suite-view/suite-view-32.jpg",
            "/images/suite-view/suite-view-33.jpg",
            "/images/suite-view/suite-view-34.jpg",
            "/images/suite-view/suite-view-35.jpg",
            "/images/suite-view/suite-view-36.jpg",
            "/images/suite-view/suite-view-37.jpg",
            "/images/suite-view/suite-view-38.jpg",
            "/images/suite-view/suite-view-39.jpg",
            "/images/suite-view/suite-view-40.jpg",
            "/images/suite-view/suite-view-41.jpg",
            "/images/suite-view/suite-view-42.jpg",
            "/images/suite-view/suite-view-43.jpg",
            "/images/suite-view/suite-view-44.jpg",
            "/images/suite-view/suite-view-45.jpg",
            "/images/suite-view/suite-view-46.jpg",
            "/images/suite-view/suite-view-47.jpg",
            "/images/suite-view/suite-view-48.jpg",
            "/images/suite-view/suite-view-49.jpg",
            "/images/suite-view/suite-view-50.jpg",
            "/images/suite-view/suite-view-51.jpg",
            "/images/suite-view/suite-view-52.jpg",
            "/images/suite-view/suite-view-53.jpg",
            "/images/suite-view/suite-view-54.jpg",
            "/images/suite-view/suite-view-55.jpg",
            "/images/suite-view/suite-view-56.jpg",
            "/images/suite-view/suite-view-57.jpg",
            "/images/suite-view/suite-view-58.jpg",
            "/images/suite-view/suite-view-59.jpg",
            "/images/suite-view/suite-view-60.jpg",
            "/images/suite-view/suite-view-61.jpg",
            "/images/suite-view/suite-view-62.jpg",
            "/images/suite-view/suite-view-63.jpg",
            "/images/suite-view/suite-view-64.jpg",
            "/images/suite-view/suite-view-65.jpg",
            "/images/suite-view/suite-view-66.jpg",
            "/images/suite-view/suite-view-67.jpg",
            "/images/suite-view/suite-view-68.jpg",
            "/images/suite-view/suite-view-69.jpg",
            "/images/suite-view/suite-view-70.jpg",
            "/images/suite-view/suite-view-71.jpg",
            "/images/suite-view/suite-view-72.jpg",
            "/images/suite-view/suite-view-73.jpg",
            "/images/suite-view/suite-view-74.jpg",
            "/images/suite-view/suite-view-75.jpg",
            "/images/suite-view/suite-view-76.jpg",
            "/images/suite-view/suite-view-77.jpg",
            "/images/suite-view/suite-view-78.jpg",
            "/images/suite-view/suite-view-79.jpg",
            "/images/suite-view/suite-view-80.jpg",
            "/images/suite-view/suite-view-81.jpg",
            "/images/suite-view/suite-view-82.jpg",
            "/images/suite-view/suite-view-83.jpg",
            "/images/suite-view/suite-view-84.jpg",
            "/images/suite-view/suite-view-85.jpg",
            "/images/suite-view/suite-view-86.jpg",
            "/images/suite-view/suite-view-87.jpg",
            "/images/suite-view/suite-view-88.jpg",
            "/images/suite-view/suite-view-89.jpg",
            "/images/suite-view/suite-view-90.jpg",
            "/images/suite-view/suite-view-91.jpg",
            "/images/suite-view/suite-view-92.jpg",
            "/images/suite-view/suite-view-93.jpg",
            "/images/suite-view/suite-view-94.jpg",
            "/images/suite-view/suite-view-95.jpg",
            "/images/suite-view/suite-view-96.jpg",
            "/images/suite-view/suite-view-97.jpg",
            "/images/suite-view/suite-view-98.jpg",
            "/images/suite-view/suite-view-99.jpg",
            "/images/suite-view/suite-view-100.jpg",
            "/images/suite-view/suite-view-101.jpg",
            "/images/suite-view/suite-view-102.jpg",
            "/images/suite-view/suite-view-103.jpg",
            "/images/suite-view/suite-view-104.jpg",
            "/images/suite-view/suite-view-105.jpg",
            "/images/suite-view/suite-view-106.jpg",
            "/images/suite-view/suite-view-107.jpg",
            "/images/suite-view/suite-view-108.jpg",
            "/images/suite-view/suite-view-109.jpg",
            "/images/suite-view/suite-view-110.jpg",
            "/images/suite-view/suite-view-111.jpg",
            "/images/suite-view/suite-view-112.jpg",
            "/images/suite-view/suite-view-113.jpg",
            "/images/suite-view/suite-view-114.jpg",
            "/images/suite-view/suite-view-115.jpg",
            "/images/suite-view/suite-view-116.jpg",
            "/images/suite-view/suite-view-117.jpg",
            "/images/suite-view/suite-view-118.jpg",
            "/images/suite-view/suite-view-119.jpg",
            "/images/suite-view/suite-view-120.jpg",
            "/images/suite-view/suite-view-121.jpg",
            "/images/suite-view/suite-view-122.jpg",
            "/images/suite-view/suite-view-123.jpg",
            "/images/suite-view/suite-view-124.jpg",
            "/images/suite-view/suite-view-125.jpg",
            "/images/suite-view/suite-view-126.jpg",
            "/images/suite-view/suite-view-127.jpg",
            "/images/suite-view/suite-view-128.jpg",
            "/images/suite-view/suite-view-129.jpg",
            "/images/suite-view/suite-view-130.jpg",
            "/images/suite-view/suite-view-131.jpg",
            "/images/suite-view/suite-view-132.jpg",
            "/images/suite-view/suite-view-133.jpg",
            "/images/suite-view/suite-view-134.jpg",
            "/images/suite-view/suite-view-135.jpg",
            "/images/suite-view/suite-view-136.jpg",
            "/images/suite-view/suite-view-137.jpg",
            "/images/suite-view/suite-view-138.jpg",
            "/images/suite-view/suite-view-139.jpg",
            "/images/suite-view/suite-view-140.jpg",
            "/images/suite-view/suite-view-141.jpg",
            "/images/suite-view/suite-view-142.jpg",
            "/images/suite-view/suite-view-143.jpg",
            "/images/suite-view/suite-view-144.jpg",
            "/images/suite-view/suite-view-145.jpg",
            "/images/suite-view/suite-view-146.jpg",
            "/images/suite-view/suite-view-147.jpg",
            "/images/suite-view/suite-view-148.jpg",
            "/images/suite-view/suite-view-149.jpg",
            "/images/suite-view/suite-view-150.jpg",
            "/images/suite-view/suite-view-151.jpg",
            "/images/suite-view/suite-view-152.jpg",
            "/images/suite-view/suite-view-153.jpg",
            "/images/suite-view/suite-view-154.jpg",
            "/images/suite-view/suite-view-155.jpg",
            "/images/suite-view/suite-view-156.jpg",
            "/images/suite-view/suite-view-157.jpg",
            "/images/suite-view/suite-view-158.jpg",
            "/images/suite-view/suite-view-159.jpg",
            "/images/suite-view/suite-view-160.jpg",
            "/images/suite-view/suite-view-161.jpg",
            "/images/suite-view/suite-view-162.jpg",
            "/images/suite-view/suite-view-163.jpg",
            "/images/suite-view/suite-view-164.jpg",
            "/images/suite-view/suite-view-165.jpg",
            "/images/suite-view/suite-view-166.jpg",
            "/images/suite-view/suite-view-167.jpg",
            "/images/suite-view/suite-view-168.jpg",
            "/images/suite-view/suite-view-169.jpg",
            "/images/suite-view/suite-view-170.jpg",
            "/images/suite-view/suite-view-171.jpg",
            "/images/suite-view/suite-view-172.jpg",
            "/images/suite-view/suite-view-173.jpg",
            "/images/suite-view/suite-view-174.jpg",
            "/images/suite-view/suite-view-175.jpg",
            "/images/suite-view/suite-view-176.jpg",
            "/images/suite-view/suite-view-177.jpg",
            "/images/suite-view/suite-view-178.jpg",
            "/images/suite-view/suite-view-179.jpg",
            "/images/suite-view/suite-view-180.jpg",
            "/images/suite-view/suite-view-181.jpg",
            "/images/suite-view/suite-view-182.jpg",
            "/images/suite-view/suite-view-183.jpg",
            "/images/suite-view/suite-view-184.jpg",
            "/images/suite-view/suite-view-185.jpg",
            "/images/suite-view/suite-view-186.jpg",
            "/images/suite-view/suite-view-187.jpg",
            "/images/suite-view/suite-view-188.jpg",
            "/images/suite-view/suite-view-189.jpg",
            "/images/suite-view/suite-view-190.jpg",
            "/images/suite-view/suite-view-191.jpg",
            "/images/suite-view/suite-view-192.jpg",
        ],
        pricePerNight: 2200,
        lat: 37.105534,
        lng: -79.652964,
        hostawayId: "466646",
    },
    {
        id: "6",
        name: "Milan Manor House",
        teaser: "A gracious manor-style home that pairs classic design with modern comforts—ideal for smaller reunions, special celebrations, or quiet retreats at the lake.",
        image: "/images/milan-manor/milan-manor-5.jpg",
        sleeps: 14,
        bedrooms: 5,
        bathrooms: 8,
        amenities: ["30 Private Acres", "Speakeasy Bar", "Pickleball Court", "Piano", "650ft Shoreline", "Historic Charm"],
        description:
            "A 1940s historic manor on 30 private acres graced by 650 feet of waterfront on Smith Mountain Lake. This exceptional estate offers five bedrooms plus a bonus room (sleeps 14), seven fireplaces, a stunning speakeasy bar, enormous chef’s kitchen, and private pickleball court—ideal for weddings, multigenerational getaways, events, or executive retreats.\\n\n" +
            "Built as a private estate where nature, wellness, and celebration intersect, the manor blends historic charm with considered design. The meticulously restored spaces flow with elegant authenticity, connecting interior rooms to expansive grounds and 650 feet of private shoreline. Throughout the home, historic touches, modern comforts, and the home’s original elevator create a backdrop for memorable weddings, events, and meaningful escapes.\\n\n" +
            "Whether gathering with loved ones, planning a lakeside celebration, or taking time away with colleagues, this landmark manor is designed for your extraordinary celebration or executive escape.",
        images: [
            "/images/milan-manor/milan-manor-1.jpg",
            "/images/milan-manor/milan-manor-2.jpg",
            "/images/milan-manor/milan-manor-3.jpg",
            "/images/milan-manor/milan-manor-4.jpg",
            "/images/milan-manor/milan-manor-5.jpg",
            "/images/milan-manor/milan-manor-6.jpg",
            "/images/milan-manor/milan-manor-7.jpg",
            "/images/milan-manor/milan-manor-8.jpg",
            "/images/milan-manor/milan-manor-9.jpg",
            "/images/milan-manor/milan-manor-10.jpg",
            "/images/milan-manor/milan-manor-11.jpg",
            "/images/milan-manor/milan-manor-12.jpg",
            "/images/milan-manor/milan-manor-13.jpg",
            "/images/milan-manor/milan-manor-14.jpg",
            "/images/milan-manor/milan-manor-15.jpg",
            "/images/milan-manor/milan-manor-16.jpg",
            "/images/milan-manor/milan-manor-17.jpg",
            "/images/milan-manor/milan-manor-18.jpg",
            "/images/milan-manor/milan-manor-19.jpg",
            "/images/milan-manor/milan-manor-20.jpg",
            "/images/milan-manor/milan-manor-21.jpg",
            "/images/milan-manor/milan-manor-22.jpg",
            "/images/milan-manor/milan-manor-23.jpg",
            "/images/milan-manor/milan-manor-24.jpg",
            "/images/milan-manor/milan-manor-25.jpg",
            "/images/milan-manor/milan-manor-26.jpg",
            "/images/milan-manor/milan-manor-27.jpg",
            "/images/milan-manor/milan-manor-28.jpg",
            "/images/milan-manor/milan-manor-29.jpg",
            "/images/milan-manor/milan-manor-30.jpg",
            "/images/milan-manor/milan-manor-31.jpg",
            "/images/milan-manor/milan-manor-32.jpg",
            "/images/milan-manor/milan-manor-33.jpg",
            "/images/milan-manor/milan-manor-34.jpg",
            "/images/milan-manor/milan-manor-35.jpg",
            "/images/milan-manor/milan-manor-36.jpg",
            "/images/milan-manor/milan-manor-37.jpg",
            "/images/milan-manor/milan-manor-38.jpg",
            "/images/milan-manor/milan-manor-39.jpg",
            "/images/milan-manor/milan-manor-40.jpg",
            "/images/milan-manor/milan-manor-41.jpg",
            "/images/milan-manor/milan-manor-42.jpg",
            "/images/milan-manor/milan-manor-43.jpg",
            "/images/milan-manor/milan-manor-44.jpg",
            "/images/milan-manor/milan-manor-45.jpg",
            "/images/milan-manor/milan-manor-46.jpg",
            "/images/milan-manor/milan-manor-47.jpg",
            "/images/milan-manor/milan-manor-48.jpg",
            "/images/milan-manor/milan-manor-49.jpg",
            "/images/milan-manor/milan-manor-50.jpg",
            "/images/milan-manor/milan-manor-51.jpg",
            "/images/milan-manor/milan-manor-52.jpg",
            "/images/milan-manor/milan-manor-53.jpg",
            "/images/milan-manor/milan-manor-54.jpg",
            "/images/milan-manor/milan-manor-55.jpg",
            "/images/milan-manor/milan-manor-56.jpg",
            "/images/milan-manor/milan-manor-57.jpg",
            "/images/milan-manor/milan-manor-58.jpg",
            "/images/milan-manor/milan-manor-59.jpg",
            "/images/milan-manor/milan-manor-60.jpg",
            "/images/milan-manor/milan-manor-61.jpg",
            "/images/milan-manor/milan-manor-62.jpg",
            "/images/milan-manor/milan-manor-63.jpg",
            "/images/milan-manor/milan-manor-64.jpg",
            "/images/milan-manor/milan-manor-65.jpg",
            "/images/milan-manor/milan-manor-66.jpg",
            "/images/milan-manor/milan-manor-67.jpg",
            "/images/milan-manor/milan-manor-68.jpg",
            "/images/milan-manor/milan-manor-69.jpg",
            "/images/milan-manor/milan-manor-70.jpg",
            "/images/milan-manor/milan-manor-71.jpg",
            "/images/milan-manor/milan-manor-72.jpg",
            "/images/milan-manor/milan-manor-73.jpg",
            "/images/milan-manor/milan-manor-74.jpg",
            "/images/milan-manor/milan-manor-75.jpg",
            "/images/milan-manor/milan-manor-76.jpg",
            "/images/milan-manor/milan-manor-77.jpg",
            "/images/milan-manor/milan-manor-78.jpg",
            "/images/milan-manor/milan-manor-79.jpg",
            "/images/milan-manor/milan-manor-80.jpg",
            "/images/milan-manor/milan-manor-81.jpg",
            "/images/milan-manor/milan-manor-82.jpg",
            "/images/milan-manor/milan-manor-83.jpg",
            "/images/milan-manor/milan-manor-84.jpg",
            "/images/milan-manor/milan-manor-85.jpg",
            "/images/milan-manor/milan-manor-86.jpg",
        ],
        pricePerNight: 1200,
        lat: 37.008306,
        lng: -79.659251,
        hostawayId: "466648",
    },
    {
        id: "7",
        name: "Penthouse View",
        teaser: "A luxury top-floor lakefront retreat with sweeping water and mountain views",
        image: "/penthouse-view.jpg",
        sleeps: 6,
        bedrooms: 2,
        bathrooms: 3,
        amenities: [
            "3 private suites",
            "Fully equipped kitchen",
            "Electric kettle",
            "Keurig, blender",
            "Wine glasses, ice bucket, wine opener",
            "Dining table for 6",
            "Board games",
            "Washer and dryer",
            "Hair dryer and iron",
            "Wi-Fi",
            "Foldable cart",
            "Elevator access",
            "Free parking",
            "Screened porch",
            "Traeger pellet grill",
            "Dock for swimming and fishing",
            "Foldable chairs",
            "Four televisions"
        ],
        description:
            "Penthouse View is a luxury top-floor lakefront retreat designed for couples, small families, and groups who want Smith Mountain Lake views with luxury amenities. The retreat features three bedrooms and three bathrooms, with stylish, comfortable living spaces oriented toward sweeping water and mountain views.\n\n" +
            "Inside, you\u2019ll find a fully equipped kitchen, in-home washer and dryer, multiple TVs, a dedicated workspace, and thoughtful \u201Cthey thought of everything\u201D touches like board games and a foldable cart to make settling in effortless.\n\n" +
            "Outside, Penthouse View delivers a resort-style feel with both screened-in and open-air decks furnished for lounging, dining, and taking in long water views. Convenient elevator access, parking, a shared dock for swimming and fishing, floating and foldable chairs, and a Traeger pellet grill keep lake days easy and enjoyable from sunrise coffee to sunset dinners.",
        images: [
            "/images/penthouse-view/penthouse-view-1.jpg",
            "/images/penthouse-view/penthouse-view-2.jpg",
            "/images/penthouse-view/penthouse-view-3.jpg",
            "/images/penthouse-view/penthouse-view-4.jpg",
            "/images/penthouse-view/penthouse-view-5.jpg",
            "/images/penthouse-view/penthouse-view-6.jpg",
            "/images/penthouse-view/penthouse-view-7.jpg",
            "/images/penthouse-view/penthouse-view-8.jpg",
            "/images/penthouse-view/penthouse-view-9.jpg",
            "/images/penthouse-view/penthouse-view-10.jpg",
            "/images/penthouse-view/penthouse-view-11.jpg",
            "/images/penthouse-view/penthouse-view-12.jpg",
            "/images/penthouse-view/penthouse-view-13.jpg",
            "/images/penthouse-view/penthouse-view-14.jpg",
            "/images/penthouse-view/penthouse-view-15.jpg",
            "/images/penthouse-view/penthouse-view-16.jpg",
            "/images/penthouse-view/penthouse-view-17.jpg",
            "/images/penthouse-view/penthouse-view-18.jpg",
            "/images/penthouse-view/penthouse-view-19.jpg",
            "/images/penthouse-view/penthouse-view-20.jpg",
            "/images/penthouse-view/penthouse-view-21.jpg",
            "/images/penthouse-view/penthouse-view-22.jpg",
            "/images/penthouse-view/penthouse-view-23.jpg",
            "/images/penthouse-view/penthouse-view-24.jpg",
            "/images/penthouse-view/penthouse-view-25.jpg",
            "/images/penthouse-view/penthouse-view-26.jpg",
            "/images/penthouse-view/penthouse-view-27.jpg",
            "/images/penthouse-view/penthouse-view-28.jpg",
            "/images/penthouse-view/penthouse-view-29.jpg",
            "/images/penthouse-view/penthouse-view-30.jpg",
            "/images/penthouse-view/penthouse-view-31.jpg",
            "/images/penthouse-view/penthouse-view-32.jpg",
            "/images/penthouse-view/penthouse-view-33.jpg",
        ],
        matterportUrl: "https://my.matterport.com/show/?m=bRM4Kkhfu6T",
        pricePerNight: 650,
        lat: 37.106738,
        lng: -79.657229,
        hostawayId: "466644",
    },
    {
        id: "5",
        name: "Lake View",
        teaser: "A stylish lakefront retreat for couples and small families seeking an intimate lake escape",
        image: "/images/lake-view/lake-view-2.jpg",
        sleeps: 4,
        bedrooms: 2,
        bathrooms: 2,
        amenities: [
            "2 private suites",
            "Fully equipped kitchen",
            "Electric kettle",
            "Keurig, blender",
            "Wine glasses, ice bucket, wine opener",
            "Dining table for 4",
            "Board games",
            "Washer and dryer",
            "Hair dryer and iron",
            "Wi-Fi",
            "Foldable cart",
            "Elevator access",
            "Free parking",
            "Screened porch",
            "Traeger pellet grill",
            "Dock for swimming and fishing",
            "Foldable chairs"
        ],
        description:
            "Lake View is a stylish, light-filled lakefront retreat designed for couples, small families, and friends who want the Wilson Premier experience in a more intimate setting. Thoughtfully laid out with comfortable bedrooms, modern bathrooms, and an open kitchen-and-living area, it\u2019s made for slow mornings, shared meals, and late-night conversations with the water in view.\n\n" +
            "Inside, you\u2019ll find a fully equipped kitchen, cozy seating, multiple TVs, and smart touches that make settling in effortless\u2014whether you\u2019re working remotely for a few days or unplugging all week. Outside, Lake View brings the best of Smith Mountain Lake right to your doorstep with a furnished balcony or patio, easy access to the water, and shared community perks like pools or docks (where applicable). From your first cup of coffee overlooking the lake to sunset drinks after a day on the water, Lake View delivers a relaxed, elevated stay that feels distinctly Wilson Premier.",
        images: [
            "/images/lake-view/lake-view-1.jpg",
            "/images/lake-view/lake-view-2.jpg",
            "/images/lake-view/lake-view-3.jpg",
            "/images/lake-view/lake-view-4.jpg",
            "/images/lake-view/lake-view-5.jpg",
            "/images/lake-view/lake-view-6.jpg",
            "/images/lake-view/lake-view-7.jpg",
            "/images/lake-view/lake-view-8.jpg",
            "/images/lake-view/lake-view-9.jpg",
            "/images/lake-view/lake-view-10.jpg",
            "/images/lake-view/lake-view-11.jpg",
            "/images/lake-view/lake-view-12.jpg",
            "/images/lake-view/lake-view-13.jpg",
            "/images/lake-view/lake-view-14.jpg",
            "/images/lake-view/lake-view-15.jpg",
            "/images/lake-view/lake-view-16.jpg",
            "/images/lake-view/lake-view-17.jpg",
            "/images/lake-view/lake-view-18.jpg",
            "/images/lake-view/lake-view-19.jpg",
            "/images/lake-view/lake-view-20.jpg",
            "/images/lake-view/lake-view-21.jpg",
            "/images/lake-view/lake-view-22.jpg",
            "/images/lake-view/lake-view-23.jpg",
            "/images/lake-view/lake-view-24.jpg",
        ],
        matterportUrl: "https://my.matterport.com/show/?m=vih9WU3PNQj",
        pricePerNight: 450,
        lat: 37.106738,
        lng: -79.657229,
        hostawayId: "466645",
    },
]

// Mock Availability Logic
export function getMockAvailability(propertyId: string, month: number, year: number): number[] {
    // Deterministic pseudo-random based on propertyId + month + year
    // seed ensures the same "random" days are always booked for a specific property/month combo
    const seed = (propertyId?.charCodeAt(0) || 0) + month + year
    const daysInMonth = new Date(year, month + 1, 0).getDate()
    const bookedDays: number[] = []

    for (let day = 1; day <= daysInMonth; day++) {
        // Simple algo to mark random days as booked (approx 20% occupancy to make it interesting)
        const pseudoRandom = Math.abs(Math.sin(seed * day * 1337))
        if (pseudoRandom > 0.8) {
            bookedDays.push(day)
        }
    }
    return bookedDays
}

export function isDateUnavailable(date: Date, propertyId?: string): boolean {
    // If no property selected, we'll be lenient and say generally available unless specifically checking
    // But for the calendar visual, we might want to show some generic busy dates if "All" is selected
    const pid = propertyId || "generic"
    const booked = getMockAvailability(pid, date.getMonth(), date.getFullYear())
    return booked.includes(date.getDate())
}
