export type ExperienceType = "restaurant" | "activity" | "attraction" | "marina" | "rental" | "park" | "winery" | "history" | "dining" | "shopping";

export interface Experience {
    id: string;
    name: string;
    type: ExperienceType;
    lat: number;
    lng: number;
    description: string;
    details: string;
    address?: string;
    hours?: string;
    phone?: string;
    website?: string;
    imageUrl?: string;
}

export const experiences: Experience[] = [
    {
        id: "sml-state-park",
        name: "Smith Mountain Lake State Park",
        type: "park",
        lat: 37.1197,
        lng: -79.6027,
        description: "The lake's premier natural destination featuring a large public beach, miles of hiking trails, and prime spots for shoreline fishing.",
        details: "1,506-acre park with 16 miles of hiking trails, swimming beach, visitor center, and stunning lake views. Offers boat rentals, cabins, and camping.",
        address: "1235 State Park Rd, Huddleston, VA 24104",
        hours: "8am - Dusk",
        phone: "(540) 297-6066",
        imageUrl: "/state-park-beach.png"
    },
    {
        id: "bridgewater-plaza",
        name: "Bridgewater Plaza",
        type: "shopping",
        lat: 37.1578,
        lng: -79.6422,
        description: "The vibrant 'hub' of the lake. Home to mini-golf, rock climbing, arcades, and some of the best waterfront dining and shopping.",
        details: "The center of action at SML. Features Fun-N-Games Arcade, Harbortown Mini Golf, rock wall, various boutiques, and multiple restaurants.",
        address: "16430 Booker T Washington Hwy, Moneta, VA 24121",
        hours: "9am - 10pm",
        phone: "(540) 721-1639",
        imageUrl: "/bridgewater-plaza.png"
    },
    {
        id: "sml-dam-visitor-center",
        name: "SML Dam & Visitor Center",
        type: "attraction",
        lat: 37.0389,
        lng: -79.5397,
        description: "A must-see architectural marvel. Offers interactive exhibits on electricity generation and stunning panoramic views of the dam.",
        details: "Learn how the dam generates clean energy. Includes a scenic overlook, picnic area, and educational displays about the history of the lake.",
        address: "2072 Ford Rd, Sandy Level, VA 24161",
        hours: "9am - 5pm (Tue-Sat)",
        phone: "(540) 985-2587",
        imageUrl: "/dam-visitor-center.png"
    },
    {
        id: "sml-jet-ski-rentals",
        name: "SML Jet Ski Rentals",
        type: "rental",
        lat: 37.1450,
        lng: -79.6300,
        description: "Experience the thrill of the open water with premium WaveRunner rentals.",
        details: "Rent the latest Yamaha WaveRunners by the hour or day. Safety equipment and brief instruction included. Reservations recommended.",
        address: "Bridgewater Plaza, Moneta, VA 24121",
        hours: "9am - 6pm Daily (May-Sept)",
        phone: "(540) 555-WAVE",
        website: "smljetski.com",
        imageUrl: "/boating-water-sports.png"
    },
    {
        id: "hickory-hill-vineyards",
        name: "Hickory Hill Vineyards",
        type: "winery",
        lat: 37.1800,
        lng: -79.6500,
        description: "A family-owned vineyard offering a peaceful atmosphere for wine tastings.",
        details: "Producing high-quality wines since 2001. Features a farmhouse tasting room, picnic area, and frequent live music events.",
        address: "1722 Hickory Cove Ln, Moneta, VA 24121",
        hours: "11am - 5pm (Wed-Sun)",
        phone: "(540) 296-1393",
        website: "hickoryhillvineyards.com",
        imageUrl: "/vineyard-tasting.png"
    },
    {
        id: "booker-t-washington-monument",
        name: "Booker T. Washington National Monument",
        type: "history",
        lat: 37.1221,
        lng: -79.7371,
        description: "Visit the birthplace of the influential educator. A living history farm glimpse into 19th-century life.",
        details: "Explore the life of Booker T. Washington through exhibits, films, and a reconstructed 1850s tobacco farm with living history demonstrations.",
        address: "12130 Booker T Washington Hwy, Hardy, VA 24101",
        hours: "9am - 5pm Daily",
        phone: "(540) 721-2094",
        imageUrl: "/historical-farm.png"
    },
    {
        id: "sml-farm-alpacas",
        name: "SML Farm Alpacas",
        type: "activity",
        lat: 37.1800,
        lng: -79.7000,
        description: "An interactive farm experience where you can meet, feed, and learn about friendly alpacas.",
        details: "Educational tours allow you to get up close with the herd. On-site shop features premium alpaca wool products.",
        address: "Call for directions, Hardy, VA",
        hours: "Tours by Appt",
        phone: "(540) 719-0281",
        imageUrl: "/alpaca-farm.png"
    },
    {
        id: "homestead-creamery",
        name: "Homestead Creamery",
        type: "dining",
        lat: 37.1257,
        lng: -79.8828,
        description: "Legendary local dairy known for high-quality glass-bottled milk and rich, creamy ice cream.",
        details: "Visit the farm market and sandwich shop. Famous for their ice cream flights and fresh dairy products distributed regionally.",
        address: "7254 Booker T Washington Hwy, Wirtz, VA 24184",
        hours: "11am - 6pm (Closed Sun)",
        phone: "(540) 721-2045",
        imageUrl: "/ice-cream-shop.png"
    },
    {
        id: "mariners-landing-golf",
        name: "Mariners Landing Golf",
        type: "activity",
        lat: 37.1350,
        lng: -79.5600,
        description: "A championship golf course designed by Robert Trent Jones Sr. with beautiful lake glimpses.",
        details: "18-hole semi-private course open to the public. Features a clubhouse, grill, and pro shop. Challenges golfers of all skill levels.",
        address: "100 Clubhouse Dr, Huddleston, VA 24104",
        hours: "7am - 6pm",
        phone: "(540) 297-7888",
        imageUrl: "/golf-course.png"
    },
    {
        id: "bernards-landing",
        name: "Bernard's Landing Resort",
        type: "marina",
        lat: 37.0673,
        lng: -79.5888,
        description: "Luxury resort community with boat rentals and 'The Landing' restaurant.",
        details: "A 70-acre waterfront peninsula with panoramic views. Offers boat rentals, beach access, wellness center, and fine dining.",
        address: "775 Ashmeade Rd, Moneta, VA 24121",
        hours: "24/7",
        phone: "(540) 721-8870",
        imageUrl: "/marina-docks.png"
    },
    {
        id: "westlake-golf-club",
        name: "Westlake Golf & Country Club",
        type: "activity",
        lat: 37.1400,
        lng: -79.6900,
        description: "Meticulously maintained links-style course winding through hardwood forests.",
        details: "18 holes of great golf designed by Russell Breeden. Known for its tight fairways and fast greens.",
        address: "360 Chestnut Creek Dr, Hardy, VA 24101",
        hours: "8am - 6pm",
        phone: "(540) 721-4214",
        imageUrl: "/golf-course.png"
    },
    {
        id: "sml-community-park",
        name: "SML Community Park",
        type: "park",
        lat: 37.1900,
        lng: -79.6400,
        description: "Peaceful 37-acre park offering a public beach, fishing pier, and scenic picnicking.",
        details: "Less crowded alternative to the State Park. Features a sandy beach (seasonal), playground, and hiking trails.",
        address: "1482 Parkway Ave, Moneta, VA 24121",
        hours: "Dawn - Dusk",
        phone: "(540) 483-9293",
        imageUrl: "/state-park-beach.png"
    },
    {
        id: "ramulose-ridge-vineyards",
        name: "Ramulose Ridge Vineyards",
        type: "winery",
        lat: 37.1600,
        lng: -79.6000,
        description: "Enjoy spectacular mountain views while sipping estate-grown wines.",
        details: "Known for their Chambourcin and Chardonel. The patio offers some of the best mountain views in the area.",
        address: "3061 Hendricks Store Rd, Moneta, VA 24121",
        hours: "11am - 5pm",
        phone: "(540) 314-2696",
        imageUrl: "/vineyard-tasting.png"
    },
    {
        id: "waterfront-restaurant",
        name: "The Waterfront Restaurant",
        type: "restaurant",
        lat: 37.1650,
        lng: -79.6380,
        description: "Fine dining at its best, featuring seasonally inspired menus and fresh seafood.",
        details: "Private country club dining open to the public. Famous for their Sunday brunch and seafood buffet events.",
        address: "22051 Virgil H Goode Hwy, Moneta, VA 24121",
        hours: "11am - 10pm",
        phone: "(540) 721-1234",
        imageUrl: "/waterfront-dining.png"
    },
    {
        id: "portside-grill",
        name: "Portside Grill & Bar",
        type: "dining",
        lat: 37.1300,
        lng: -79.6100,
        description: "The quintessential lakeside 'dock and dine' experience. Casual fare and tropical drinks.",
        details: "Virginia's only Key West style bar & grill. Entirely outdoors/covered. Live music weekends.",
        address: "3619 Airport Rd, Moneta, VA 24121",
        hours: "11am - 10pm (Seasonal)",
        phone: "(540) 297-7100",
        imageUrl: "/waterfront-dining.png"
    },
    {
        id: "crazy-horse-marina",
        name: "Crazy Horse Marina",
        type: "marina",
        lat: 37.0500,
        lng: -79.6100,
        description: "Full-service marina with pontoon rentals and a popular seasonal restaurant.",
        details: "Home to Los Amigos Mexican restaurant. Large covered slips, gas dock, and ship store.",
        address: "400 Crazy Horse Dr, Moneta, VA 24121",
        hours: "9am - 6pm",
        phone: "(540) 719-0620",
        imageUrl: "/marina-docks.png"
    },
    {
        id: "harvester-center",
        name: "Harvester Performance Center",
        type: "activity",
        lat: 36.9946,
        lng: -79.8911,
        description: "State-of-the-art venue hosting world-class musical acts in an intimate setting.",
        details: "Renowned mid-sized music venue attracting major national touring acts. Great sightlines and acoustics.",
        address: "450 Franklin St, Rocky Mount, VA 24151",
        hours: "Show times vary",
        phone: "(540) 484-8277",
        imageUrl: "/bridgewater-plaza.png"
    },
    {
        id: "sml-kayak-tours",
        name: "Guided Kayak Tours",
        type: "activity",
        lat: 37.1100,
        lng: -79.6200,
        description: "Explore hidden coves and peaceful inlets with expert guides on a serene kayaking adventure.",
        details: "Eco-friendly tours showcasing the lake's natural beauty. Single and tandem kayaks available. Sunset tours are especially popular.",
        address: "Various launch points around SML",
        hours: "8am - 7pm (Seasonal)",
        phone: "(540) 555-KYAK",
        imageUrl: "/boating-water-sports.png"
    },
    {
        id: "fishing-charter-sml",
        name: "Captain's Choice Fishing Charters",
        type: "activity",
        lat: 37.0900,
        lng: -79.5800,
        description: "Professional guided fishing trips targeting striped bass, largemouth bass, and catfish.",
        details: "Half-day and full-day charters with all equipment provided. Captain has 20+ years experience on SML waters.",
        address: "Departs from multiple marinas",
        hours: "Dawn - Dusk",
        phone: "(540) 555-FISH",
        imageUrl: "/fishing-recreation.png"
    },
    {
        id: "sunset-dinner-cruise",
        name: "Sunset Dinner Cruise",
        type: "activity",
        lat: 37.1200,
        lng: -79.6000,
        description: "An unforgettable evening aboard a luxury yacht with gourmet dining and breathtaking sunset views.",
        details: "Three-course meal prepared by award-winning chef. BYOB welcome. Reservations required, limited capacity.",
        address: "Bridgewater Marina",
        hours: "Departs 6:30pm (Summer)",
        phone: "(540) 555-CRSE",
        imageUrl: "/sunset-cruises.png"
    },
    {
        id: "lakeside-spa",
        name: "Serenity Lakeside Spa",
        type: "activity",
        lat: 37.1450,
        lng: -79.6350,
        description: "Indulge in rejuvenating treatments with panoramic lake views from every treatment room.",
        details: "Full-service spa offering massages, facials, body treatments, and couples packages. Outdoor relaxation deck.",
        address: "Bridgewater Plaza, Moneta, VA 24121",
        hours: "9am - 7pm Daily",
        phone: "(540) 555-RELX",
        imageUrl: "/waterfront-dining.png"
    },
    {
        id: "sml-hiking-trails",
        name: "Chestnut Ridge Trail System",
        type: "park",
        lat: 37.1600,
        lng: -79.6700,
        description: "Network of scenic hiking trails ranging from easy lakeside walks to challenging mountain climbs.",
        details: "12 miles of well-maintained trails with varying difficulty. Stunning overlooks, wildlife viewing, and seasonal wildflowers.",
        address: "Trailhead: Chestnut Creek Rd, Hardy, VA",
        hours: "Dawn - Dusk",
        imageUrl: "/state-park-beach.png"
    },
    {
        id: "farmers-market-sml",
        name: "Smith Mountain Lake Farmers Market",
        type: "shopping",
        lat: 37.1700,
        lng: -79.6500,
        description: "Weekly market featuring local produce, artisan crafts, baked goods, and live music.",
        details: "Over 40 vendors offering farm-fresh vegetables, honey, jams, handmade soaps, and regional specialties.",
        address: "Community Park, Moneta, VA",
        hours: "8am - 12pm Saturdays (May-Oct)",
        phone: "(540) 555-FARM",
        imageUrl: "/ice-cream-shop.png"
    },
    {
        id: "lakeside-art-gallery",
        name: "Waters Edge Art Gallery",
        type: "shopping",
        lat: 37.1550,
        lng: -79.6400,
        description: "Curated collection of regional artists featuring lake-inspired paintings, pottery, and sculpture.",
        details: "Rotating exhibits, artist meet-and-greets, and workshops. Specializes in Blue Ridge and lake landscape art.",
        address: "16450 Booker T Washington Hwy, Moneta, VA",
        hours: "10am - 5pm (Wed-Sun)",
        phone: "(540) 555-ARTS",
        imageUrl: "/bridgewater-plaza.png"
    },
    {
        id: "pontoon-boat-rentals",
        name: "Paradise Pontoon Rentals",
        type: "rental",
        lat: 37.1100,
        lng: -79.6150,
        description: "Spacious pontoon boats perfect for family outings, swimming, and leisurely lake exploration.",
        details: "Fleet of 20-24 foot pontoons with Bimini tops. Half-day and full-day rentals. Coolers and life jackets included.",
        address: "Multiple marina locations",
        hours: "8am - 6pm Daily (Apr-Oct)",
        phone: "(540) 555-PONT",
        imageUrl: "/boating-water-sports.png"
    },
    {
        id: "lakefront-yoga",
        name: "Sunrise Lakefront Yoga",
        type: "activity",
        lat: 37.1250,
        lng: -79.6050,
        description: "Start your day with peaceful yoga sessions on a floating dock as the sun rises over the water.",
        details: "All levels welcome. Mats and props provided. Private sessions and SUP yoga also available.",
        address: "State Park Beach Area",
        hours: "6:30am Daily (Summer)",
        phone: "(540) 555-YOGA",
        imageUrl: "/state-park-beach.png"
    },
    {
        id: "sml-brewery",
        name: "Blue Ridge Lakeside Brewery",
        type: "dining",
        lat: 37.1350,
        lng: -79.6250,
        description: "Craft brewery with rotating taps, wood-fired pizza, and a dog-friendly lakefront patio.",
        details: "Award-winning IPAs and seasonal brews. Live music Fridays and Saturdays. Growler fills available.",
        address: "1850 Scruggs Rd, Moneta, VA",
        hours: "12pm - 10pm (Closed Mon-Tue)",
        phone: "(540) 555-BREW",
        imageUrl: "/waterfront-dining.png"
    },
    {
        id: "wakeboard-school",
        name: "SML Wakeboard Academy",
        type: "activity",
        lat: 37.0950,
        lng: -79.5950,
        description: "Professional instruction for wakeboarding, waterskiing, and wake surfing for all skill levels.",
        details: "Certified instructors, top-tier equipment, and dedicated coaching boats. Beginner to advanced lessons.",
        address: "Hales Ford Marina",
        hours: "9am - 6pm Daily (May-Sept)",
        phone: "(540) 555-WAKE",
        imageUrl: "/boating-water-sports.png"
    },
    {
        id: "fall-festival",
        name: "Smith Mountain Lake Fall Festival",
        type: "activity",
        lat: 37.1200,
        lng: -79.6100,
        description: "Annual autumn celebration with craft vendors, live music, food trucks, and family activities.",
        details: "Held every October. Features pumpkin patch, hayrides, local artisans, and stunning fall foliage views.",
        address: "Community Park, Moneta, VA",
        hours: "10am - 6pm (Mid-October)",
        phone: "(540) 555-FEST",
        imageUrl: "/bridgewater-plaza.png"
    },
    {
        id: "fireworks-cruise",
        name: "4th of July Fireworks Cruise",
        type: "activity",
        lat: 37.1150,
        lng: -79.6000,
        description: "Celebrate Independence Day with the best seat on the lake for the spectacular fireworks show.",
        details: "Two-hour cruise with premium viewing location. Light refreshments included. Books up months in advance.",
        address: "Departs Bridgewater Marina",
        hours: "8pm - 10:30pm (July 4th)",
        phone: "(540) 555-JULY",
        imageUrl: "/sunset-cruises.png"
    }
]
